# Generated by Django 5.0 on 2023-12-18 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event_topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('slug', models.CharField(max_length=200, null=True)),
                ('event_topic_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event_topics.eventtopic')),
            ],
            options={
                'indexes': [models.Index(fields=['slug', 'event_topic_id'], name='event_sub_t_slug_e7fe13_idx')],
            },
        ),
    ]
