# Generated by Django 5.0 on 2024-01-28 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event_topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=2147483647, null=True)),
                ('slug', models.CharField(blank=True, max_length=2147483647, null=True)),
                ('event_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event_topics.eventtopic')),
            ],
            options={
                'unique_together': {('slug', 'event_topic')},
            },
        ),
    ]
