# Generated by Django 5.0 on 2024-03-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
