# Generated by Django 5.0 on 2024-03-14 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_discountcode_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2147483647)),
                ('subtitle', models.CharField(max_length=2147483647, null=True)),
                ('short_abstract', models.TextField(null=True)),
                ('long_abstract', models.TextField(null=True)),
                ('comments', models.TextField(null=True)),
                ('starts_at', models.DateTimeField(null=True)),
                ('ends_at', models.DateTimeField(null=True)),
                ('language', models.CharField(max_length=2147483647, null=True)),
                ('slides_url', models.CharField(max_length=2147483647, null=True)),
                ('video_url', models.CharField(max_length=2147483647, null=True)),
                ('audio_url', models.CharField(max_length=2147483647, null=True)),
                ('signup_url', models.CharField(max_length=2147483647, null=True)),
                ('state', models.CharField(max_length=2147483647, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('submitted_at', models.DateTimeField(null=True)),
                ('submission_modifier', models.CharField(max_length=2147483647, null=True)),
                ('is_mail_sent', models.BooleanField(null=True)),
                ('level', models.CharField(max_length=2147483647, null=True)),
                ('last_modified_at', models.DateTimeField(null=True)),
                ('send_email', models.BooleanField(null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('complex_field_values', models.JSONField(null=True)),
                ('average_rating', models.FloatField(default=0.0, null=True)),
                ('rating_count', models.IntegerField(default=0)),
                ('facebook', models.CharField(max_length=2147483647, null=True)),
                ('github', models.CharField(max_length=2147483647, null=True)),
                ('gitlab', models.CharField(max_length=2147483647, null=True)),
                ('instagram', models.CharField(max_length=2147483647, null=True)),
                ('linkedin', models.CharField(max_length=2147483647, null=True)),
                ('twitter', models.CharField(max_length=2147483647, null=True)),
                ('website', models.CharField(max_length=2147483647, null=True)),
                ('favourite_count', models.IntegerField(default=0)),
                ('mastodon', models.CharField(max_length=2147483647, null=True)),
                ('slides', models.JSONField(max_length=2147483647, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=2147483647, null=True)),
                ('length', models.CharField(blank=True, max_length=2147483647, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('color', models.CharField(max_length=200, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('position', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Microlocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2147483647, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('floor', models.IntegerField(null=True)),
                ('room', models.CharField(max_length=2147483647, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('position', models.IntegerField(null=True)),
                ('hidden_in_scheduler', models.BooleanField(default=False)),
                ('is_chat_enabled', models.BooleanField(blank=True, null=True)),
                ('is_global_event_room', models.BooleanField(blank=True, null=True)),
                ('chat_room_id', models.CharField(blank=True, max_length=2147483647, null=True)),
                ('event_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
