# Generated by Django 5.0 on 2024-03-14 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_sessions_sessiontypes_tracks_microlocations'),
        ('video_channels', '0002_videostreams'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='microlocations',
            name='video_stream_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='video_channels.videostreams'),
        ),
        migrations.AddField(
            model_name='sessions',
            name='creator_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessions',
            name='event_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AddField(
            model_name='sessions',
            name='microlocation_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.microlocations'),
        ),
        migrations.AddField(
            model_name='sessiontypes',
            name='event_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event'),
        ),
        migrations.AddField(
            model_name='sessions',
            name='session_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.sessiontypes'),
        ),
        migrations.AddField(
            model_name='tracks',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AddField(
            model_name='sessions',
            name='track_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.tracks'),
        ),
    ]
