version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: cryptography
    versions:
    - "> 3.3.2, < 4"
  - dependency-name: sqlalchemy
    versions:
    - "> 1.3.23, < 2"
  - dependency-name: flask-jwt-extended
    versions:
    - 4.0.2
    - 4.1.0
