FORMAT: V1
HOST: http://nextgen.eventyay.com

# Orga-Server

The Open Event API Server

## Users Collection [/users?page,limit]

### List All Users [GET]

+ Request

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json)

        {
          "meta": {
            "count": 1
          },
          "data": [
            {
              "attributes": {
                "created_at": "2017-06-01T01:24:47.500127+00:00",
                "google": null,
                "instagram": null,
                "firstname": null,
                "lastname": null,
                "twitter": null,
                "signup_at": "2017-06-01T01:25:07.385816+00:00",
                "is_super_admin": true,
                "thumbnail": null,
                "email": "me@ipiyush.com",
                "avatar": null,
                "contact": null,
                "is_admin": true,
                "details": null,
                "last_accessed_at": null,
                "small": null,
                "facebook": null,
                "deleted_at": null,
                "is_verified": true,
                "avatar_uploaded": null,
                "icon": null
              },
              "type": "user",
              "id": "1",
              "links": {
                "self": "/v1/users/1"
              }
            }
          ],
          "jsonapi": {
            "version": "1.0"
          },
          "links": {
            "self": "/v1/users"
          }
        }


### Create User [POST]

+ name (string) - Name of the user
+ passowrd (string) - Password of the user
+ email (string) - Email of the user

+ Request (application/vnd.api+json)

        {
            "name": "Open Event User",
            "email": "example@example.com",
            "password": "12345678
        }

+ Response 200 (application/vnd.api+json)
    
        {
            'data': 'data'
        }

## User Details [/users/{user_id}]
+ Parameters
    + user_id (integer) - ID of the user in the form of an integer
    
### Get Details [GET]
+ Request

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json)
    
        {
          "data": {
            "attributes": {
              "created_at": "2017-06-01T01:24:47.500127+00:00",
              "google": null,
              "instagram": null,
              "firstname": null,
              "lastname": null,
              "twitter": null,
              "signup_at": "2017-06-01T01:25:07.385816+00:00",
              "is_super_admin": true,
              "thumbnail": null,
              "email": "me@ipiyush.com",
              "avatar": null,
              "contact": null,
              "is_admin": true,
              "details": null,
              "last_accessed_at": null,
              "small": null,
              "facebook": null,
              "deleted_at": null,
              "is_verified": true,
              "avatar_uploaded": null,
              "icon": null
            },
            "type": "user",
            "id": "1",
            "links": {
              "self": "/v1/users/1"
            }
          },
          "jsonapi": {
            "version": "1.0"
          },
          "links": {
            "self": "/v1/users/1"
          }
        }

        
### Update User [PATCH]

+ Response 200 (application/vnd.api+json)
    
        {
          "data": {
            "attributes": {
              "created_at": "2017-06-01T01:24:47.500127+00:00",
              "google": null,
              "instagram": null,
              "firstname": null,
              "lastname": null,
              "twitter": null,
              "signup_at": "2017-06-01T01:25:07.385816+00:00",
              "is_super_admin": true,
              "thumbnail": null,
              "email": "me@ipiyush.com",
              "avatar": null,
              "contact": null,
              "is_admin": true,
              "details": null,
              "last_accessed_at": null,
              "small": null,
              "facebook": null,
              "deleted_at": null,
              "is_verified": true,
              "avatar_uploaded": null,
              "icon": null
            },
            "type": "user",
            "id": "1",
            "links": {
              "self": "/v1/users/1"
            }
          },
          "jsonapi": {
            "version": "1.0"
          },
          "links": {
            "self": "/v1/users/1"
          }
        }

### Delete User [DELETE]

+ Response 204
