# Generated by Django 5.0 on 2023-12-23 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Microlocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2147483647)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('room', models.CharField(blank=True, max_length=2147483647, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('position', models.IntegerField(default=0)),
                ('hidden_in_scheduler', models.BooleanField(default=False)),
                ('is_chat_enabled', models.BooleanField(blank=True, null=True)),
                ('is_global_event_room', models.BooleanField(blank=True, null=True)),
                ('chat_room_id', models.CharField(blank=True, max_length=2147483647, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
