apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: {{ include "open-event.name" . }}
    helm.sh/chart: {{ include "open-event.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: {{ include "open-event.name" . }}
  name: celery-generated
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.celery.storage.generated.size}}
