# Generated by Django 5.0 on 2024-04-14 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('event_topics', '0001_initial'), ('event_topics', '0002_eventsubtopic')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.CharField(max_length=200)),
                ('system_image_url', models.URLField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventSubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('slug', models.CharField(max_length=200, null=True)),
                ('event_topic_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event_topics.eventtopic')),
            ],
        ),
    ]
