# Group Event Export

This group of APIs help you to start a task for exporting a particular event in the zip format, ical and xcal. It also lets you start a task to export orders of an event as csv

## Start Event Export as Zip [/v1/events/{event_identifier}/export/json]
This endpoint lets the user start a task of exporting the event in the zip format.
+ Parameters
    + event_identifier: 1 (string) - identifier or event id of the event. (b8324ae2 is an example of identifier)
Start a celery task to export the event with the event_id as a collection of json files and archive it to get it ready for downloading. Returns the task url
to get the status of the export task.


### Start a Task to Export an Event as Zip [POST]

+ Request

    + Headers

            Content-Type: application/vnd.api+json
            Authorization: JWT <Auth Key>

    + Body

            {
                "image": true,
                "video": true,
                "document": true,
                "audio": true
            }

+ Response 200 (application/json)

        {
            "task_url":"/v1/tasks/b7ca7088-876e-4c29-a0ee-b8029a64849a"
        }

## Start Event Export as iCal file [/v1/events/{event_identifier}/export/ical]
This endpoint lets the user start a task to export the event as an iCal file.
+ Parameters
    + event_identifier: 1 (string) - identifier or event id of the event. (b8324ae2 is an example of identifier)
Start a celery task to export the event with the event_id as an iCal event file.

### Start a Task to Export an Event as iCal event [GET]

+ Request

    + Headers

            Authorization: JWT <Auth Key>

+ Response 200 (application/json)

        {
            "task_url":"/v1/tasks/b7ca7088-876e-4c29-a0ee-b8029a64849a"
        }

## Start Event Export as xCalendar [/v1/events/{event_identifier}/export/xcal]
+ Parameters
    + event_identifier: 1 (string) - identifier or event id of the event. (b8324ae2 is an example of identifier)
Start a celery task to export the event with the event_id as an xcal file to get it ready for downloading. Returns the task url
to get the status of the export task.


### Start a Task to Export an Event as xCalendar [GET]

+ Request

    + Headers

            Authorization: JWT <Auth Key>

+ Response 200 (application/json)

        {
            "task_url":"/v1/tasks/b7ca7088-876e-4c29-a0ee-b8029a64849a"
        }

## Start Event Export as Pentabarf XML [/v1/events/{event_identifier}/export/pentabarf]
+ Parameters
    + event_identifier: 1 (string) - identifier or event id of the event. (b8324ae2 is an example of identifier)
Start a celery task to export the event with the event_id as a pentabarf XML file to get it ready for downloading. Returns the task url
to get the status of the export task.


### Start a Task to Export an Event as Pentabarf XML [GET]

+ Request

    + Headers

            Authorization: JWT <Auth Key>

+ Response 200 (application/json)

        {
            "task_url":"/v1/tasks/b7ca7088-876e-4c29-a0ee-b8029a64849a"
        }

## Start Orders Export as CSV [/v1/events/{event_identifier}/export/orders/csv]
+ Parameters
    + event_identifier: 1 (string) - identifier or event id of the event. (b8324ae2 is an example of identifier)
Start a celery task to export the list of orders of the event with that event_id as a CSV file to get it ready for downloading. Returns the task url
to get the status of the export task.


### Start a Task to Export Orders of an Event as CSV [GET]

+ Request

    + Headers

            Authorization: JWT <Auth Key>

+ Response 200 (application/json)

        {
            "task_url":"/v1/tasks/b7ca7088-876e-4c29-a0ee-b8029a64849a"
        }

## Start Orders Export as PDF [/v1/events/{event_identifier}/export/orders/pdf]
+ Parameters
    + event_identifier: 1 (string) - identifier or event id of the event. (b8324ae2 is an example of identifier)
Start a celery task to export the list of orders of the event with that event_id as a PDF file to get it ready for downloading. Returns the task url
to get the status of the export task.


### Start a Task to Export Orders of an Event as PDF [GET]

+ Request

    + Headers

            Authorization: JWT <Auth Key>

+ Response 200 (application/json)

        {
            "task_url":"/v1/tasks/b7ca7088-876e-4c29-a0ee-b8029a64849a"
        }

## Start Attendees Export as CSV [/v1/events/{event_identifier}/export/attendees/csv]
+ Parameters
    + event_identifier: 1 (string) - identifier or event id of the event. (b8324ae2 is an example of identifier)
Start a celery task to export the list of attendees of the event with that event_id as a CSV file to get it ready for downloading. Returns the task url
to get the status of the export task.


### Start a Task to Export Attendees of an Event as CSV [GET]

+ Request

    + Headers

            Authorization: JWT <Auth Key>

+ Response 200 (application/json)

        {
            "task_url":"/v1/tasks/b7ca7088-876e-4c29-a0ee-b8029a64849a"
        }

## Start Attendees Export as PDF [/v1/events/{event_identifier}/export/attendees/pdf]
+ Parameters
    + event_identifier: 1 (string) - identifier or event id of the event. (b8324ae2 is an example of identifier)
Start a celery task to export the list of attendees of the event with that event_id as a PDF file to get it ready for downloading. Returns the task url
to get the status of the export task.


### Start a Task to Export Attendees of an Event as PDF [GET]

+ Request

    + Headers

            Authorization: JWT <Auth Key>

+ Response 200 (application/json)

        {
            "task_url":"/v1/tasks/b7ca7088-876e-4c29-a0ee-b8029a64849a"
        }

## Start Sessions Export as CSV [/v1/events/{event_identifier}/export/sessions/csv]
+ Parameters
    + event_identifier: 1 (string) - identifier or event id of the event. (b8324ae2 is an example of identifier)
Start a celery task to export the list of sessions of the event with that event_id as a CSV file to get it ready for downloading. Returns the task url
to get the status of the export task.


### Start a Task to Export Sessions of an Event as CSV [POST]

+ Request

    + Headers

            Content-Type: application/vnd.api+json
            Authorization: JWT <Auth Key>
    
    + Body

            {
                "status": "all"
            }

+ Response 200 (application/json)

        {
            "task_url":"/v1/tasks/b7ca7088-876e-4c29-a0ee-b8029a64849a"
        }

## Start Speakers Export as CSV [/v1/events/{event_identifier}/export/speakers/csv]
+ Parameters
    + event_identifier: 1 (string) - identifier or event id of the event. (b8324ae2 is an example of identifier)
Start a celery task to export the list of speakers of the event with that event_id as a CSV file to get it ready for downloading. Returns the task url
to get the status of the export task.


### Start a Task to Export Speakers of an Event as CSV [POST]

+ Request

    + Headers

            Content-Type: application/vnd.api+json
            Authorization: JWT <Auth Key>
    
    + Body

            {
                "status": "all"
            }
        

+ Response 200 (application/json)

        {
            "task_url":"/v1/tasks/b7ca7088-876e-4c29-a0ee-b8029a64849a"
        }

## Start Sessions Export as PDF [/v1/events/{event_identifier}/export/sessions/pdf]
+ Parameters
    + event_identifier: 1 (string) - identifier or event id of the event. (b8324ae2 is an example of identifier)
Start a celery task to export the list of sessions of the event with that event_id as a PDF file to get it ready for downloading. Returns the task url
to get the status of the export task.


### Start a Task to Export Sessions of an Event as PDF [GET]

+ Request

    + Headers

            Authorization: JWT <Auth Key>

+ Response 200 (application/json)

        {
            "task_url":"/v1/tasks/b7ca7088-876e-4c29-a0ee-b8029a64849a"
        }

## Start Speakers Export as PDF [/v1/events/{event_identifier}/export/speakers/pdf]
+ Parameters
    + event_identifier: 1 (string) - identifier or event id of the event. (b8324ae2 is an example of identifier)
Start a celery task to export the list of speakers of the event with that event_id as a PDF file to get it ready for downloading. Returns the task url
to get the status of the export task.


### Start a Task to Export Speakers of an Event as PDF [GET]

+ Request

    + Headers

            Authorization: JWT <Auth Key>

+ Response 200 (application/json)

        {
            "task_url":"/v1/tasks/b7ca7088-876e-4c29-a0ee-b8029a64849a"
        }
