# Group Event Copy

To create copy of an event

## Create Event Copy [/v1/events/{identifier}/copy]
+ Parameters
    + identifier: 1 - Identifier of the event or ID of the event to copy
Creates the copy. Requires Co-Organizer access

### Create Copy [POST]

+ Request

    + Headers

            Content-Type: application/vnd.api+json
            Authorization: JWT <Auth Key>

    + Body

            {}

+ Response 200 (application/json)

        {
          "copied": true,
          "id": 25,
          "identifier": "52d69149"
        }
