# Group Event Types

Event Types for Events. Can only be edited and entered by admins.


| Parameter | Description | Type | Required |
|:----------|-------------|------|----------|
| `name`  | Name of the event type | string | - |
| `slug` | Slug of the event type | string | - |


## Event Types Collection [/v1/event-types{?page%5bsize%5d,page%5bnumber%5d,sort}]
+ Parameters
    + page%5bsize%5d (optional, integer, `10`) - Maximum number of resources in a single paginated response.
    + page%5bnumber%5d (optional, integer, `2`) - Page number to fetched for the paginated response.
    + sort (optional, string, `name`) - Sort the resources according to the given attribute in ascending order. Append '-' to sort in descending order.

### List All Event Types [GET]
Get a list of Event Types.

+ Request

    + Headers

            Accept: application/vnd.api+json

            Authorization: JWT <Auth Key>

+ Response 200 (application/vnd.api+json)

        {
          "meta": {
            "count": 1
          },
          "data": [
            {
              "relationships": {
                "events": {
                  "links": {
                    "self": "/v1/event-types/1/relationships/events",
                    "related": "/v1/event-types/1/events"
                  }
                }
              },
              "attributes": {
                "name": "Camp, Treat & Retreat",
                "slug": "camp-treat-retreat"
              },
              "type": "event-type",
              "id": "1",
              "links": {
                "self": "/v1/event-types/1"
              }
            }
          ],
          "jsonapi": {
            "version": "1.0"
          },
          "links": {
            "self": "/v1/event-types"
          }
        }


### Create Event Type [POST]
Create a new event type with name.

+ Request (application/vnd.api+json)

    + Headers

            Authorization: JWT <Auth Key>

    + Body

            {
              "data": {
                "attributes": {
                  "name": "Camp, Treat & Retreat"
                },
                "type": "event-type"
              }
            }

+ Response 201 (application/vnd.api+json)

        {
            "data": {
              "relationships": {
                "events": {
                  "links": {
                    "self": "/v1/event-types/1/relationships/events",
                    "related": "/v1/event-types/1/events"
                  }
                }
              },
              "attributes": {
                "name": "Camp, Treat & Retreat",
                "slug": "camp-treat-retreat"
              },
              "type": "event-type",
              "id": "1",
              "links": {
                "self": "/v1/event-types/1"
              }
            },
            "jsonapi": {
              "version": "1.0"
            },
            "links": {
              "self": "/v1/event-types/1"
            }
          }

## Event Type Details [/v1/event-types/{event_type_id}]
+ Parameters
    + event_type_id: 1 (integer) - ID of the event type in the form of an integer

### Event Type Details [GET]
Get a single event type.

+ Request

    + Headers

            Accept: application/vnd.api+json

            Authorization: JWT <Auth Key>

+ Response 200 (application/vnd.api+json)

        {
          "data": {
            "relationships": {
              "events": {
                "links": {
                  "self": "/v1/event-types/1/relationships/events",
                  "related": "/v1/event-types/1/events"
                }
              }
            },
            "attributes": {
              "name": "Camp, Treat & Retreat",
              "slug": "camp-treat-retreat"
            },
            "type": "event-type",
            "id": "1",
            "links": {
              "self": "/v1/event-types/1"
            }
          },
          "jsonapi": {
            "version": "1.0"
          },
          "links": {
            "self": "/v1/event-types/1"
          }
        }


### Update Event Type [PATCH]
+ `id` (integer) - ID of the record to update **(required)**

Update a single event type by setting name.

Authorized user must be admin.

+ Request (application/vnd.api+json)

    + Headers

            Authorization: JWT <Auth Key>

    + Body

            {
              "data": {
                "attributes": {
                  "name": "Camp, Treat & Retreat"
                },
                "type": "event-type",
                "id": "1"
              }
            }

+ Response 200 (application/vnd.api+json)

        {
            "data": {
              "relationships": {
                "events": {
                  "links": {
                    "self": "/v1/event-types/1/relationships/events",
                    "related": "/v1/event-types/1/events"
                  }
                }
              },
              "attributes": {
                "name": "Camp, Treat & Retreat",
                "slug": "camp-treat-retreat"
              },
              "type": "event-type",
              "id": "1",
              "links": {
                "self": "/v1/event-types/1"
              }
            },
            "jsonapi": {
              "version": "1.0"
            },
            "links": {
              "self": "/v1/event-types/1"
            }
          }

### Delete Event Type [DELETE]
Delete a single event type.

+ Request

    + Headers

            Accept: application/vnd.api+json

            Authorization: JWT <Auth Key>

+ Response 200 (application/vnd.api+json)

        {
          "meta": {
            "message": "Object successfully deleted"
          },
          "jsonapi": {
            "version": "1.0"
          }
        }


## Event Type of an Event [/v1/events/{event_identifier}/event-type]
+ Parameters
    + event_identifier: 1 (string) - identifier or event id of the event. (b8324ae2 is an example of identifier)

### Event Type Details of an Event [GET]
Get a single event type.

+ Request

    + Headers

            Accept: application/vnd.api+json

            Authorization: JWT <Auth Key>

+ Response 200 (application/vnd.api+json)


        {
            "data": {
                "relationships": {
                    "events": {
                        "links": {
                            "self": "/v1/event-types/1/relationships/events",
                            "related": "/v1/event-types/1/events"
                        }
                    }
                },
                "attributes": {
                    "name": "Camp, Treat & Retreat",
                    "slug": "camp-treat-retreat"
                },
                "type": "event-type",
                "id": "1",
                "links": {
                    "self": "/v1/event-types/1"
                }
            },
            "jsonapi": {
                "version": "1.0"
            },
            "links": {
                "self": "/v1/event-types/1"
            }
        }
