# Generated by Django 5.0 on 2023-12-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PanelPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_name', models.CharField(blank=True, max_length=200, null=True)),
                ('can_access', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
