# Generated by Django 5.0 on 2026-01-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('recipients', models.CharField(choices=[('attendees', 'Attendees'), ('speakers', 'Speakers'), ('all', 'All')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent')], default='pending', max_length=20)),
                ('created_by', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
