# Generated by Django 5.0 on 2026-01-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_mails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmail',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventmail',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
