# Generated by Django 5.0 on 2026-01-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_mails', '0002_eventmail_delete_eventtopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmail',
            name='event_id',
            field=models.IntegerField(db_index=True, help_text='ID of the event from events table'),
        ),
    ]
