"""empty message

Revision ID: 0044c9631c7e
Revises: f375453ca1f6
Create Date: 2018-08-01 15:09:21.572471

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0044c9631c7e'
down_revision = 'f375453ca1f6'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_chat_message', sa.Column('label', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_chat_message', 'label')
    # ### end Alembic commands ###
