"""empty message

Revision ID: 00ea66754d06
Revises: 41494520d7c0
Create Date: 2016-06-13 15:21:12.410712

"""

# revision identifiers, used by Alembic.
revision = '00ea66754d06'
down_revision = '41494520d7c0'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_form', sa.String(), nullable=False),
    sa.Column('speaker_form', sa.String(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custom_forms')
    ### end Alembic commands ###
