"""empty message

Revision ID: 010744bcdb8d
Revises: 32881ff3b521
Create Date: 2017-08-25 15:44:51.175284

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '010744bcdb8d'
down_revision = '32881ff3b521'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faq_types',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('event_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('faq', sa.Column('faq_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'faq', 'faq_types', ['faq_type_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'faq', type_='foreignkey')
    op.drop_column('faq', 'faq_type_id')
    op.drop_table('faq_types')
    # ### end Alembic commands ###
