"""empty message

Revision ID: 06aad85a9091
Revises: 91ee86a38001
Create Date: 2019-02-20 21:50:47.821540

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06aad85a9091'
down_revision = '91ee86a38001'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('instagram_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('instargam_login_hash', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['instagram_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'instargam_login_hash')
    op.drop_column('users', 'instagram_id')
    # ### end Alembic commands ###
