"""empty message

Revision ID: 06e3dc4e8d68
Revises: 8a3b434d8265
Create Date: 2016-06-11 20:49:27.304470

"""

# revision identifiers, used by Alembic.
revision = '06e3dc4e8d68'
down_revision = '8a3b434d8265'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_for_papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('announcement', sa.Text(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'sponsors', sa.Column('level', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'sponsors', 'level')
    op.drop_table('call_for_papers')
    ### end Alembic commands ###
