"""empty message

Revision ID: 09c86e38f5e7
Revises: a6e5abbcc205
Create Date: 2019-06-12 12:12:24.692657

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '09c86e38f5e7'
down_revision = 'a6e5abbcc205'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('show_remaining_tickets', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('events_version', sa.Column('show_remaining_tickets', sa.Boolean(), server_default='False', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events_version', 'show_remaining_tickets')
    op.drop_column('events', 'show_remaining_tickets')
    # ### end Alembic commands ###
