"""empty message

Revision ID: 0ebd913edd27
Revises: 2f9f90ee6e73
Create Date: 2016-10-17 20:05:36.663421

"""

# revision identifiers, used by Alembic.
revision = '0ebd913edd27'
down_revision = '2f9f90ee6e73'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('created_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'created_at')
    ### end Alembic commands ###
