"""empty message

Revision ID: 1552f7bafb5b
Revises: f2b4430d9e57
Create Date: 2016-06-16 19:53:16.684181

"""

# revision identifiers, used by Alembic.
revision = '1552f7bafb5b'
down_revision = 'f2b4430d9e57'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
