"""empty message

Revision ID: 16183eae08cb
Revises: 3458fec198e2
Create Date: 2017-06-22 21:02:54.903603

"""

# revision identifiers, used by Alembic.
revision = '16183eae08cb'
down_revision = '3458fec198e2'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('static_domain', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'static_domain')
    ### end Alembic commands ###
