"""empty message

Revision ID: 193fadf22de7
Revises: 98166ca15055
Create Date: 2016-05-31 11:40:12.637151

"""

# revision identifiers, used by Alembic.
revision = '193fadf22de7'
down_revision = '98166ca15055'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.String(), nullable=True))
    op.add_column('user', sa.Column('tokens', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'tokens')
    op.drop_column('user', 'avatar')
    ### end Alembic commands ###
