"""empty message

Revision ID: 1a89015d90bd
Revises: a9b15f3c5424
Create Date: 2017-01-23 17:33:18.737072

"""

# revision identifiers, used by Alembic.
revision = '1a89015d90bd'
down_revision = 'a9b15f3c5424'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('trashed_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'trashed_at')
    ### end Alembic commands ###
