"""empty message

Revision ID: 1b34cefe5f92
Revises: 10136334dff5
Create Date: 2016-06-18 13:32:26.921934

"""

# revision identifiers, used by Alembic.
revision = '1b34cefe5f92'
down_revision = '10136334dff5'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('session_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'session', 'session_type', ['session_type_id'], ['id'])
    op.drop_constraint(u'session_type_session_id_fkey', 'session_type', type_='foreignkey')
    op.drop_column('session_type', 'session_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_type', sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'session_type_session_id_fkey', 'session_type', 'session', ['session_id'], ['id'])
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.drop_column('session', 'session_type_id')
    ### end Alembic commands ###
