"""empty message

Revision ID: 1b3e4f5f56bd
Revises: d84f976530e1
Create Date: 2016-06-14 22:00:05.729214

"""

# revision identifiers, used by Alembic.
revision = '1b3e4f5f56bd'
down_revision = 'd84f976530e1'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'call_for_papers_event_id_fkey', 'call_for_papers', type_='foreignkey')
    op.create_foreign_key(None, 'call_for_papers', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(u'custom_forms_event_id_fkey', 'custom_forms', type_='foreignkey')
    op.create_foreign_key(None, 'custom_forms', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(u'eventsusers_event_id_fkey', 'eventsusers', type_='foreignkey')
    op.create_foreign_key(None, 'eventsusers', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(u'invites_event_id_fkey', 'invites', type_='foreignkey')
    op.create_foreign_key(None, 'invites', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(u'microlocation_event_id_fkey', 'microlocation', type_='foreignkey')
    op.create_foreign_key(None, 'microlocation', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(u'session_event_id_fkey', 'session', type_='foreignkey')
    op.create_foreign_key(None, 'session', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(u'session_type_event_id_fkey', 'session_type', type_='foreignkey')
    op.create_foreign_key(None, 'session_type', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(u'social_link_event_id_fkey', 'social_link', type_='foreignkey')
    op.create_foreign_key(None, 'social_link', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(u'speaker_event_id_fkey', 'speaker', type_='foreignkey')
    op.create_foreign_key(None, 'speaker', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(u'sponsor_type_event_id_fkey', 'sponsor_type', type_='foreignkey')
    op.create_foreign_key(None, 'sponsor_type', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(u'sponsors_event_id_fkey', 'sponsors', type_='foreignkey')
    op.create_foreign_key(None, 'sponsors', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(u'tracks_event_id_fkey', 'tracks', type_='foreignkey')
    op.create_foreign_key(None, 'tracks', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(u'users_events_roles_event_id_fkey', 'users_events_roles', type_='foreignkey')
    op.create_foreign_key(None, 'users_events_roles', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_events_roles', type_='foreignkey')
    op.create_foreign_key(u'users_events_roles_event_id_fkey', 'users_events_roles', 'events', ['event_id'], ['id'])
    op.drop_constraint(None, 'tracks', type_='foreignkey')
    op.create_foreign_key(u'tracks_event_id_fkey', 'tracks', 'events', ['event_id'], ['id'])
    op.drop_constraint(None, 'sponsors', type_='foreignkey')
    op.create_foreign_key(u'sponsors_event_id_fkey', 'sponsors', 'events', ['event_id'], ['id'])
    op.drop_constraint(None, 'sponsor_type', type_='foreignkey')
    op.create_foreign_key(u'sponsor_type_event_id_fkey', 'sponsor_type', 'events', ['event_id'], ['id'])
    op.drop_constraint(None, 'speaker', type_='foreignkey')
    op.create_foreign_key(u'speaker_event_id_fkey', 'speaker', 'events', ['event_id'], ['id'])
    op.drop_constraint(None, 'social_link', type_='foreignkey')
    op.create_foreign_key(u'social_link_event_id_fkey', 'social_link', 'events', ['event_id'], ['id'])
    op.drop_constraint(None, 'session_type', type_='foreignkey')
    op.create_foreign_key(u'session_type_event_id_fkey', 'session_type', 'events', ['event_id'], ['id'])
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.create_foreign_key(u'session_event_id_fkey', 'session', 'events', ['event_id'], ['id'])
    op.drop_constraint(None, 'microlocation', type_='foreignkey')
    op.create_foreign_key(u'microlocation_event_id_fkey', 'microlocation', 'events', ['event_id'], ['id'])
    op.drop_constraint(None, 'invites', type_='foreignkey')
    op.create_foreign_key(u'invites_event_id_fkey', 'invites', 'events', ['event_id'], ['id'])
    op.drop_constraint(None, 'eventsusers', type_='foreignkey')
    op.create_foreign_key(u'eventsusers_event_id_fkey', 'eventsusers', 'events', ['event_id'], ['id'])
    op.drop_constraint(None, 'custom_forms', type_='foreignkey')
    op.create_foreign_key(u'custom_forms_event_id_fkey', 'custom_forms', 'events', ['event_id'], ['id'])
    op.drop_constraint(None, 'call_for_papers', type_='foreignkey')
    op.create_foreign_key(u'call_for_papers_event_id_fkey', 'call_for_papers', 'events', ['event_id'], ['id'])
    ### end Alembic commands ###
