"""empty message

Revision ID: 1c52a25b4a97
Revises: 42b10433d1b3
Create Date: 2018-06-16 20:16:31.341637

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c52a25b4a97'
down_revision = '42b10433d1b3'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_holders', sa.Column('attendee_notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_holders', 'attendee_notes')
    # ### end Alembic commands ###
