"""empty message

Revision ID: 1c6f7e989021
Revises: c4b4889d5e4e
Create Date: 2017-04-15 01:27:43.288320

"""

# revision identifiers, used by Alembic.
revision = '1c6f7e989021'
down_revision = 'c4b4889d5e4e'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'trash_date', new_column_name='deleted_at')
    op.drop_column('events', 'in_trash')
    op.alter_column('events_version', 'trash_date', new_column_name='deleted_at')
    op.drop_column('events_version', 'in_trash')
    op.alter_column('session', 'trash_date', new_column_name='deleted_at')
    op.drop_column('session', 'in_trash')
    op.alter_column('session_version', 'trash_date', new_column_name='deleted_at')
    op.drop_column('session_version', 'in_trash')
    op.alter_column('user', 'trash_date', new_column_name='deleted_at')
    op.drop_column('user', 'in_trash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('in_trash', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('user', 'deleted_at', new_column_name='trash_date')
    op.add_column('session_version', sa.Column('in_trash', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('session_version', 'deleted_at', new_column_name='trash_date')
    op.add_column('session', sa.Column('in_trash', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('session', 'deleted_at', new_column_name='trash_date')
    op.add_column('events_version', sa.Column('in_trash', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('events_version', 'deleted_at', new_column_name='trash_date')
    op.add_column('events', sa.Column('in_trash', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('events', 'deleted_at', new_column_name='trash_date')
    # ### end Alembic commands ###
