"""empty message

Revision ID: 1c7441698fae
Revises: 8223e1b0c247
Create Date: 2016-08-16 07:27:26.885072

"""

# revision identifiers, used by Alembic.
revision = '1c7441698fae'
down_revision = '8223e1b0c247'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('verified_user', sa.Boolean(), nullable=True),
    sa.Column('unverified_user', sa.Boolean(), nullable=True),
    sa.Column('anonymous_user', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_permissions')
    ### end Alembic commands ###
