"""empty message

Revision ID: 1cc66579a10e
Revises: ca3156df9a12
Create Date: 2016-08-02 13:20:49.465992

"""

# revision identifiers, used by Alembic.
revision = '1cc66579a10e'
down_revision = 'ca3156df9a12'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'events', sa.Column('paypal_email', sa.String(), nullable=True))
    op.add_column(u'events', sa.Column('tax_allow', sa.Boolean(), nullable=True))
    op.add_column(u'events_version', sa.Column('paypal_email', sa.String(), autoincrement=False, nullable=True))
    op.add_column(u'events_version', sa.Column('tax_allow', sa.Boolean(), autoincrement=False, nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'events_version', 'tax_allow')
    op.drop_column(u'events_version', 'paypal_email')
    op.drop_column(u'events', 'tax_allow')
    op.drop_column(u'events', 'paypal_email')
    ### end Alembic commands ###
