"""empty message

Revision ID: 1d4ae4569284
Revises: 24da7df1e00e
Create Date: 2017-06-30 22:45:17.510988

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = '1d4ae4569284'
down_revision = '24da7df1e00e'


def upgrade():
    # commands auto generated by Alembic - please adjust! #
    op.alter_column('tickets', 'description_toggle', new_column_name='is_description_visible')
    # end Alembic commands #


def downgrade():
    # commands auto generated by Alembic - please adjust! #
    op.alter_column('tickets', 'is_description_visible', new_column_name='description_toggle')
    # end Alembic commands #
