"""empty message

Revision ID: 202b15987640
Revises: 30ca70296a1c
Create Date: 2016-03-27 14:36:59.712765

"""

# revision identifiers, used by Alembic.
revision = '202b15987640'
down_revision = '30ca70296a1c'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_email_unique', 'user', ['email'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_email_unique', 'user', type_='unique')
    ### end Alembic commands ###
