"""empty message
Revision ID: 20b836df74cc
Revises: 2b1ace2d613d
Create Date: 2018-05-25 01:46:53.292127
"""

from alembic import op
import sqlalchemy as sa
from flask import current_app as app, request
import urllib.parse

# revision identifiers, used by Alembic.
revision = '20b836df74cc'
down_revision = '2b1ace2d613d'

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_topics', sa.Column(
        'system_image_url', sa.String()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_topics', 'system_image_url')
    # ### end Alembic commands ###
