"""empty message
Revision ID: 20b836df74cc
Revises: 6440077182f0
Create Date: 2018-05-25 01:46:53.292127
"""

from alembic import op
import sqlalchemy as sa
from flask import current_app as app, request
import urllib.parse

# revision identifiers, used by Alembic.
revision = '20b836df74cc'
down_revision = '6440077182f0'

def set_default_sys_image():
    with app.request_context():
        url = urllib.parse.urlparse(request.url)
        image_url = url.scheme + '://' + url.netloc + '/static/header.png'
        return image_url

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_topics', sa.Column(
        'system_image_url', sa.String(), server_default=set_default_sys_image()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_topics', 'system_image_url')
    # ### end Alembic commands ###
