"""empty message

Revision ID: 2281c3f3b984
Revises: 6581466d21c9
Create Date: 2017-01-04 20:58:11.880708

"""

# revision identifiers, used by Alembic.
revision = '2281c3f3b984'
down_revision = '6581466d21c9'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_detail', sa.Column('instagram', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_detail', 'instagram')
    # ### end Alembic commands ###
