"""empty message

Revision ID: 23ff3fbdc6da
Revises: 8c777b781ea8
Create Date: 2016-08-24 15:21:12.866610

"""

# revision identifiers, used by Alembic.
revision = '23ff3fbdc6da'
down_revision = '8c777b781ea8'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_sizes', sa.Column('logo_height', sa.Integer(), nullable=True))
    op.add_column('image_sizes', sa.Column('logo_width', sa.Integer(), nullable=True))
    op.add_column('image_sizes', sa.Column('profile_width', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_sizes', 'profile_width')
    op.drop_column('image_sizes', 'logo_width')
    op.drop_column('image_sizes', 'logo_height')
    ### end Alembic commands ###
