"""empty message

Revision ID: 24da7df1e00e
Revises: 52d175c3da98
Create Date: 2017-06-27 16:32:54.671408

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '24da7df1e00e'
down_revision = '52d175c3da98'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'hide', new_column_name='is_hidden')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'is_hidden', new_column_name='hide')
    # ### end Alembic commands ###
