"""empty message

Revision ID: 26a83ff1e6ad
Revises: aa4b21539f5b
Create Date: 2016-06-16 17:34:53.524263

"""

# revision identifiers, used by Alembic.
revision = '26a83ff1e6ad'
down_revision = 'aa4b21539f5b'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'session_language_id_fkey', 'session', type_='foreignkey')
    op.drop_table('language')
    op.drop_column('session', 'language_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('language_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'session_language_id_fkey', 'session', 'language', ['language_id'], ['id'])
    op.create_table('language',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('label_en', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('label_de', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'language_pkey')
    )
    ### end Alembic commands ###
