"""empty message

Revision ID: 26b8a1438602
Revises: ec7d4c35740b
Create Date: 2016-07-24 09:45:40.779201

"""

# revision identifiers, used by Alembic.
revision = '26b8a1438602'
down_revision = 'ec7d4c35740b'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apscheduler_jobs')
    op.add_column('events', sa.Column('trash_date', sa.DateTime(), nullable=True))
    op.drop_column('events', 'in_trash_date')
    op.add_column('events_version', sa.Column('trash_date', sa.DateTime(), autoincrement=False, nullable=True))
    op.drop_column('events_version', 'in_trash_date')
    op.add_column('session', sa.Column('timezone', sa.String(), nullable=False))
    op.add_column('session_version', sa.Column('timezone', sa.String(), autoincrement=False, nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_version', 'timezone')
    op.drop_column('session', 'timezone')
    op.add_column('events_version', sa.Column('in_trash_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('events_version', 'trash_date')
    op.add_column('events', sa.Column('in_trash_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('events', 'trash_date')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'apscheduler_jobs_pkey')
    )
    ### end Alembic commands ###
