"""empty message

Revision ID: 2b1ace2d613d
Revises: f552e3e64bf8
Create Date: 2018-07-22 04:04:52.573000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b1ace2d613d'
down_revision = 'f552e3e64bf8'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('paypal_braintree_sandbox_access_token', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('paypal_braintree_access_token', sa.String(), nullable=True))
    op.drop_column('settings', 'paypal_live_username')
    op.drop_column('settings', 'paypal_sandbox_signature')
    op.drop_column('settings', 'paypal_live_signature')
    op.drop_column('settings', 'paypal_live_password')
    op.drop_column('settings', 'paypal_sandbox_password')
    op.drop_column('settings', 'paypal_sandbox_username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('paypal_sandbox_username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('settings', sa.Column('paypal_sandbox_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('settings', sa.Column('paypal_live_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('settings', sa.Column('paypal_live_signature', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('settings', sa.Column('paypal_sandbox_signature', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('settings', sa.Column('paypal_live_username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('settings', 'paypal_braintree_sandbox_access_token')
    op.drop_column('settings', 'paypal_braintree_access_token')
    # ### end Alembic commands ###
