"""empty message

Revision ID: 2c7ff9781032
Revises: b08a4ffff5dd
Create Date: 2019-06-21 04:33:59.021835

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '2c7ff9781032'
down_revision = 'b08a4ffff5dd'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'order_expiry_time')
    op.drop_column('events_version', 'order_expiry_time')
    op.add_column('settings', sa.Column('order_expiry_time', sa.Integer(), server_default='15', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'order_expiry_time')
    op.add_column('events_version', sa.Column('order_expiry_time', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('order_expiry_time', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
