"""empty message

Revision ID: 2eb08848b0e9
Revises: 53500e542289
Create Date: 2016-08-09 18:35:00.407000

"""

# revision identifiers, used by Alembic.
revision = '2eb08848b0e9'
down_revision = '53500e542289'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('identifier', sa.String(), nullable=True))
    op.add_column('events_version', sa.Column('identifier', sa.String(), autoincrement=False, nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events_version', 'identifier')
    op.drop_column('events', 'identifier')
    ### end Alembic commands ###
