"""empty message

Revision ID: 3538731a796a
Revises: c4b4889d5e4e
Create Date: 2017-04-14 14:44:16.052281

"""

# revision identifiers, used by Alembic.
revision = '3538731a796a'
down_revision = 'c4b4889d5e4e'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('access_codes', 'created_at', new_column_name='created_at_date_time')
    op.alter_column('access_codes', 'valid_from', new_column_name='valid_from_date_time')
    op.alter_column('access_codes', 'valid_till', new_column_name='valid_till_date_time')
    op.alter_column('discount_codes', 'created_at', new_column_name='created_at_date_time')
    op.alter_column('discount_codes', 'valid_from', new_column_name='valid_from_date_time')
    op.alter_column('discount_codes', 'valid_till', new_column_name='valid_till_date_time')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('access_codes', 'created_at_date_time', new_column_name='created_at')
    op.alter_column('access_codes', 'valid_from_date_time', new_column_name='valid_from')
    op.alter_column('access_codes', 'valid_till_date_time', new_column_name='valid_till')
    op.alter_column('discount_codes', 'created_at_date_time', new_column_name='created_at')
    op.alter_column('discount_codes', 'valid_from_date_time', new_column_name='valid_from')
    op.alter_column('discount_codes', 'valid_till_date_time', new_column_name='valid_till')

    ### end Alembic commands ###
