"""empty message

Revision ID: 35f427e85075
Revises: 565ea5bc3937
Create Date: 2019-03-20 21:25:31.304161

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '35f427e85075'
down_revision = '565ea5bc3937'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions_speakers_links',
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('speaker_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('session_state', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='sessions_speakers_links_pkey')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions_speakers_links')
    # ### end Alembic commands ###
