"""empty message

Revision ID: 37208b5daa39
Revises: b15e124e9b93
Create Date: 2017-06-10 13:21:54.300078

"""

# revision identifiers, used by Alembic.
revision = '37208b5daa39'
down_revision = 'bae57b0ae2cd'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sponsors', 'sponsor_type', new_column_name='type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sponsors', 'type', new_column_name='sponsor_type')
    # ### end Alembic commands ###
