"""empty message

Revision ID: 3a01b7d9d55e
Revises: 163f9fc56815
Create Date: 2018-07-08 21:00:30.438784

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '3a01b7d9d55e'
down_revision = '163f9fc56815'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_fees', sa.Column('country', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_fees', 'country')
    # ### end Alembic commands ###
