"""empty message

Revision ID: 3a1e54b1be78
Revises: 66c7787c546e
Create Date: 2016-08-01 21:58:15.889094

"""

# revision identifiers, used by Alembic.
revision = '3a1e54b1be78'
down_revision = '66c7787c546e'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('android_app_url', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('web_app_url', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'web_app_url')
    op.drop_column('settings', 'android_app_url')
    ### end Alembic commands ###
