"""empty message

Revision ID: 3a9c159811ae
Revises: acc80f4a90d2
Create Date: 2016-08-05 20:48:57.697000

"""

# revision identifiers, used by Alembic.
revision = '3a9c159811ae'
down_revision = 'acc80f4a90d2'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discount_codes', sa.Column('tickets', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discount_codes', 'tickets')
    ### end Alembic commands ###
