"""empty message

Revision ID: 3b55af20871a
Revises: 072706cab017
Create Date: 2016-05-19 11:42:06.856851

"""

# revision identifiers, used by Alembic.
revision = '3b55af20871a'
down_revision = '072706cab017'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('state', sa.String(), nullable=True))
    op.drop_constraint(u'events_name_key', 'events', type_='unique')
    op.add_column('eventsusers', sa.Column('role', sa.String(), nullable=False))
    op.drop_column('user', 'tokens')
    op.drop_column('user', 'avatar')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('tokens', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('eventsusers', 'role')
    op.create_unique_constraint(u'events_name_key', 'events', ['name'])
    op.drop_column('events', 'state')
    ### end Alembic commands ###
