"""empty message

Revision ID: 3c88cd5a4967
Revises: 00ea66754d06
Create Date: 2016-06-14 03:33:11.431801

"""

# revision identifiers, used by Alembic.
revision = '3c88cd5a4967'
down_revision = '00ea66754d06'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invites', sa.Column('session_id', sa.Integer, nullable=True))
    op.create_foreign_key(None, 'invites', 'session', ['session_id'], ['id'], ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invites', type_='foreignkey')
    op.drop_column('invites', 'session_id')
    ### end Alembic commands ###
