"""empty message

Revision ID: 3cff160c9a1d
Revises: 32c2b9dac053
Create Date: 2015-06-02 11:33:57.983932

"""

# revision identifiers, used by Alembic.
revision = '3cff160c9a1d'
down_revision = '32c2b9dac053'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('event_ver', sa.Integer(), nullable=False),
    sa.Column('session_ver', sa.Integer(), nullable=False),
    sa.Column('speakers_ver', sa.Integer(), nullable=False),
    sa.Column('tracks_ver', sa.Integer(), nullable=False),
    sa.Column('sponsors_ver', sa.Integer(), nullable=False),
    sa.Column('microlocations_ver', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('versions')
    ### end Alembic commands ###
