"""empty message

Revision ID: 3ea3ef8796a8
Revises: 7871961f26f2
Create Date: 2016-07-21 11:54:04.600472

"""

# revision identifiers, used by Alembic.
revision = '3ea3ef8796a8'
down_revision = '7871961f26f2'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'versions', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'versions', type_='foreignkey')
    ### end Alembic commands ###
