"""empty message

Revision ID: 3f145ecaf358
Revises: ac2a9daf5a8e
Create Date: 2016-12-08 16:05:03.406224

"""

# revision identifiers, used by Alembic.
revision = '3f145ecaf358'
down_revision = 'ac2a9daf5a8e'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'discount_codes_event_id_fkey', 'discount_codes', type_='foreignkey')
    op.drop_constraint(u'discount_codes_marketer_id_fkey', 'discount_codes', type_='foreignkey')
    op.create_foreign_key(None, 'discount_codes', 'user', ['marketer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'discount_codes', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(u'event_invoices_user_id_fkey', 'event_invoices', type_='foreignkey')
    op.create_foreign_key(None, 'event_invoices', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(u'eventsusers_user_id_fkey', 'eventsusers', type_='foreignkey')
    op.create_foreign_key(None, 'eventsusers', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(u'invites_user_id_fkey', 'invites', type_='foreignkey')
    op.create_foreign_key(None, 'invites', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(u'notification_user_id_fkey', 'notification', type_='foreignkey')
    op.create_foreign_key(None, 'notification', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(u'permissions_service_id_fkey', 'permissions', type_='foreignkey')
    op.drop_constraint(u'permissions_role_id_fkey', 'permissions', type_='foreignkey')
    op.create_foreign_key(None, 'permissions', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'permissions', 'service', ['service_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(u'role_invite_role_id_fkey', 'role_invite', type_='foreignkey')
    op.create_foreign_key(None, 'role_invite', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(u'session_session_type_id_fkey', 'session', type_='foreignkey')
    op.drop_constraint(u'session_microlocation_id_fkey', 'session', type_='foreignkey')
    op.drop_constraint(u'session_track_id_fkey', 'session', type_='foreignkey')
    op.create_foreign_key(None, 'session', 'microlocation', ['microlocation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'session', 'tracks', ['track_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'session', 'session_type', ['session_type_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(u'speaker_user_id_fkey', 'speaker', type_='foreignkey')
    op.create_foreign_key(None, 'speaker', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(u'ticket_holders_order_id_fkey', 'ticket_holders', type_='foreignkey')
    op.create_foreign_key(None, 'ticket_holders', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(u'user_detail_user_id_fkey', 'user_detail', type_='foreignkey')
    op.create_foreign_key(None, 'user_detail', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_detail', type_='foreignkey')
    op.create_foreign_key(u'user_detail_user_id_fkey', 'user_detail', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'ticket_holders', type_='foreignkey')
    op.create_foreign_key(u'ticket_holders_order_id_fkey', 'ticket_holders', 'orders', ['order_id'], ['id'])
    op.drop_constraint(None, 'speaker', type_='foreignkey')
    op.create_foreign_key(u'speaker_user_id_fkey', 'speaker', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.create_foreign_key(u'session_track_id_fkey', 'session', 'tracks', ['track_id'], ['id'])
    op.create_foreign_key(u'session_microlocation_id_fkey', 'session', 'microlocation', ['microlocation_id'], ['id'])
    op.create_foreign_key(u'session_session_type_id_fkey', 'session', 'session_type', ['session_type_id'], ['id'])
    op.drop_constraint(None, 'role_invite', type_='foreignkey')
    op.create_foreign_key(u'role_invite_role_id_fkey', 'role_invite', 'role', ['role_id'], ['id'])
    op.drop_constraint(None, 'permissions', type_='foreignkey')
    op.drop_constraint(None, 'permissions', type_='foreignkey')
    op.create_foreign_key(u'permissions_role_id_fkey', 'permissions', 'role', ['role_id'], ['id'])
    op.create_foreign_key(u'permissions_service_id_fkey', 'permissions', 'service', ['service_id'], ['id'])
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.create_foreign_key(u'notification_user_id_fkey', 'notification', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'invites', type_='foreignkey')
    op.create_foreign_key(u'invites_user_id_fkey', 'invites', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'eventsusers', type_='foreignkey')
    op.create_foreign_key(u'eventsusers_user_id_fkey', 'eventsusers', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'event_invoices', type_='foreignkey')
    op.create_foreign_key(u'event_invoices_user_id_fkey', 'event_invoices', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'discount_codes', type_='foreignkey')
    op.drop_constraint(None, 'discount_codes', type_='foreignkey')
    op.create_foreign_key(u'discount_codes_marketer_id_fkey', 'discount_codes', 'user', ['marketer_id'], ['id'])
    op.create_foreign_key(u'discount_codes_event_id_fkey', 'discount_codes', 'events', ['event_id'], ['id'])
    ### end Alembic commands ###
