"""empty message

Revision ID: 41818fe31207
Revises: 73d11d219aa7
Create Date: 2018-08-13 00:43:07.917523

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '41818fe31207'
down_revision = '73d11d219aa7'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('is_donation_enabled', sa.Boolean(), nullable=True))
    op.add_column('events_version', sa.Column('is_donation_enabled', sa.Boolean(),
                  autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events_version', 'is_donation_enabled')
    op.drop_column('events', 'is_donation_enabled')
    # ### end Alembic commands ###
