"""empty message

Revision ID: 42a3c1d7f4d8
Revises: None
Create Date: 2015-05-30 00:47:00.800985

"""

# revision identifiers, used by Alembic.
revision = '42a3c1d7f4d8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('color', sa.String(), nullable=True))
    op.add_column('events', sa.Column('email', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'email')
    op.drop_column('events', 'color')
    ### end Alembic commands ###
