"""empty message

Revision ID: 44e7397c1cae
Revises: 0ebd913edd27
Create Date: 2016-10-24 19:04:41.051294

"""

# revision identifiers, used by Alembic.
revision = '44e7397c1cae'
down_revision = '0ebd913edd27'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('state_email_sent', sa.Boolean(), nullable=True))
    op.add_column('session_version', sa.Column('state_email_sent', sa.Boolean(), autoincrement=False, nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_version', 'state_email_sent')
    op.drop_column('session', 'state_email_sent')
    ### end Alembic commands ###
