"""empty message

Revision ID: 460a04b3e98e
Revises: 2680911b5a1a
Create Date: 2016-06-03 03:15:49.128795

"""

# revision identifiers, used by Alembic.
revision = '460a04b3e98e'
down_revision = 'd796a713eba3'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('description', sa.Text(), nullable=True))
    op.drop_column('events', 'slogan')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('slogan', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('events', 'description')
    ### end Alembic commands ###
