"""empty message

Revision ID: 4b9a4e5aebe6
Revises: 2b39d8c05788
Create Date: 2017-07-22 16:27:08.943285

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4b9a4e5aebe6'
down_revision = '2b39d8c05788'


def upgrade():
    # commands auto generated by Alembic - please adjust! #
    op.add_column('role_invites', sa.Column('role_name', sa.String(), nullable=True))
    op.execute('UPDATE role_invites SET role_name=(SELECT name FROM roles WHERE id = role_invites.role_id)')
    op.execute('DELETE FROM role_invites WHERE role_name IS NULL')
    op.alter_column('role_invites', 'role_name',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    # end Alembic commands ###


def downgrade():
    # commands auto generated by Alembic - please adjust! #
    op.drop_column('role_invites', 'role_name')
    # end Alembic commands #
