"""empty message

Revision ID: 4bdb4809f519
Revises: 4279c2ac565b
Create Date: 2019-07-02 12:58:07.279306

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '4bdb4809f519'
down_revision = '43e8c59337ag'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('admin_billing_state', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('invoice_sending_day', sa.Integer(), server_default='1', nullable=False))
    op.add_column('settings', sa.Column('invoice_sending_timezone', sa.String(), server_default='UTC', nullable=False))
    op.add_column('users', sa.Column('billing_state', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'billing_state')
    op.drop_column('settings', 'invoice_sending_day')
    op.drop_column('settings', 'invoice_sending_timezone')
    op.drop_column('settings', 'admin_billing_state')
    # ### end Alembic commands ###
