"""empty message

Revision ID: 4defe72abed3
Revises: 85e24937f108
Create Date: 2017-07-24 21:29:53.336389

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '4defe72abed3'
down_revision = '85e24937f108'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sessions', 'users', ['creator_id'], ['id'], ondelete='CASCADE')
    op.add_column('sessions_version', sa.Column('creator_id', sa.Integer(), autoincrement=False, nullable=True))
    op.execute("""UPDATE events SET state = LOWER(state)""")
    op.execute("""UPDATE events SET state = 'draft' WHERE state != 'published'""")
    op.execute("""UPDATE sessions SET state = LOWER(state)""")
    op.execute("""UPDATE sessions SET state = 'draft' WHERE state not in
    ('accepted', 'pending', 'confirmed', 'rejected')""")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions_version', 'creator_id')
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'creator_id')
    # ### end Alembic commands ###
