"""empty message

Revision ID: 4e5dd0df14b5
Revises: fb3114b70f3c
Create Date: 2016-08-06 21:20:17.660000

"""

# revision identifiers, used by Alembic.
revision = '4e5dd0df14b5'
down_revision = 'fb3114b70f3c'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('stripe_client_id', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'stripe_client_id')
    ### end Alembic commands ###
