"""empty message

Revision ID: 4e882b5acaaa
Revises: 06e3dc4e8d68
Create Date: 2016-06-12 09:49:16.369892

"""

# revision identifiers, used by Alembic.
revision = '4e882b5acaaa'
down_revision = '06e3dc4e8d68'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_for_papers', sa.Column('event_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'call_for_papers', 'events', ['event_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'call_for_papers', type_='foreignkey')
    op.drop_column('call_for_papers', 'event_id')
    ### end Alembic commands ###
