"""empty message

Revision ID: 50ea4564df21
Revises: a48d69ccb5e3
Create Date: 2017-02-12 15:56:15.566220

"""

# revision identifiers, used by Alembic.
revision = '50ea4564df21'
down_revision = 'a48d69ccb5e3'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders_tickets', sa.Column('ticket_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders_tickets', 'ticket', ['ticket_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders_tickets', type_='foreignkey')
    op.drop_column('orders_tickets', 'ticket_id')
    # ### end Alembic commands ###
