"""empty message

Revision ID: 5155b2a9f3fc
Revises: 42a7c7ff2a8e
Create Date: 2016-12-31 13:51:02.970890

"""

# revision identifiers, used by Alembic.
revision = '5155b2a9f3fc'
down_revision = '42a7c7ff2a8e'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session_type', 'length',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.String(),
               existing_nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session_type', 'length',
               existing_type=sa.String(),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    ### end Alembic commands ###
