"""empty message

Revision ID: 52fe3ae3d39e
Revises: 1c7e0ce885a6
Create Date: 2016-10-17 19:53:22.991756

"""

# revision identifiers, used by Alembic.
revision = '52fe3ae3d39e'
down_revision = '1c7e0ce885a6'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_invoices', sa.Column('discount_code_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'event_invoices', 'discount_codes', ['discount_code_id'], ['id'], ondelete='SET NULL')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_invoices', type_='foreignkey')
    op.drop_column('event_invoices', 'discount_code_id')
    ### end Alembic commands ###
