"""empty message

Revision ID: 54bd9a22f763
Revises: acfe483fecb3
Create Date: 2019-06-06 00:12:57.500330

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '54bd9a22f763'
down_revision = 'acfe483fecb3'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_discount_codes', 'discount_codes', type_='unique')
    op.alter_column('events', 'is_ngo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('events_version', 'is_ngo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False,
               existing_server_default=sa.text('false'))
    op.alter_column('events_version', 'is_ticket_form_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False,
               existing_server_default=sa.text('true'))
    op.alter_column('sessions_version', 'is_locked',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions_version', 'is_locked',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False,
               existing_server_default=sa.text('false'))
    op.alter_column('events_version', 'is_ticket_form_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False,
               existing_server_default=sa.text('true'))
    op.alter_column('events_version', 'is_ngo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False,
               existing_server_default=sa.text('false'))
    op.alter_column('events', 'is_ngo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_unique_constraint('uq_discount_codes', 'discount_codes', ['event_id', 'code'])
    # ### end Alembic commands ###
