"""empty message

Revision ID: 591df081093e
Revises: 623663663ec8
Create Date: 2016-06-15 20:02:13.858000

"""

# revision identifiers, used by Alembic.
revision = '591df081093e'
down_revision = '623663663ec8'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('speaker', sa.Column('mobile', sa.String(), nullable=True))
    op.alter_column('speaker', 'web', new_column_name='website')
    op.alter_column('speaker', 'biography', new_column_name='short_biography')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('speaker', 'mobile')
    op.alter_column('speaker', 'website', new_column_name='web')
    op.alter_column('speaker', 'short_biography', new_column_name='biography')
    ### end Alembic commands ###
