"""empty message

Revision ID: 59d045580f02
Revises: 4f2f0d9fe9e1
Create Date: 2016-08-25 03:21:38.619558

"""

# revision identifiers, used by Alembic.
revision = '59d045580f02'
down_revision = '4f2f0d9fe9e1'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_sizes', sa.Column('full_quality', sa.Integer(), nullable=True))
    op.add_column('image_sizes', sa.Column('icon_quality', sa.Integer(), nullable=True))
    op.add_column('image_sizes', sa.Column('thumbnail_quality', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_sizes', 'thumbnail_quality')
    op.drop_column('image_sizes', 'icon_quality')
    op.drop_column('image_sizes', 'full_quality')
    ### end Alembic commands ###
