"""empty message

Revision ID: 5aed7e80e00e
Revises: 81a713eded64
Create Date: 2017-01-11 17:32:14.599285

"""

# revision identifiers, used by Alembic.
revision = '5aed7e80e00e'
down_revision = '81a713eded64'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('absorb_fees', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'absorb_fees')
    ### end Alembic commands ###
