"""empty message

Revision ID: 5b5cec07a402
Revises: ba651e8ce9a3
Create Date: 2019-07-16 10:07:05.795451

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '5b5cec07a402'
down_revision = 'ba651e8ce9a3'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('invoice_pdf_url', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('is_event_invoice', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'is_event_invoice')
    op.drop_column('orders', 'invoice_pdf_url')
    # ### end Alembic commands ###
