"""empty message

Revision ID: 5b9f83cede65
Revises: 4591885edbf0
Create Date: 2018-04-18 17:55:43.266248

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '5b9f83cede65'
down_revision = '4591885edbf0'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket_holders', 'pdf_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket_holders', 'pdf_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
