"""empty message

Revision ID: 5d35fa753afa
Revises: 01b6969ef4e5
Create Date: 2016-06-29 10:26:02.416966

"""

# revision identifiers, used by Alembic.
revision = '5d35fa753afa'
down_revision = '01b6969ef4e5'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'invites_session_id_fkey', 'invites', type_='foreignkey')
    op.create_foreign_key(None, 'invites', 'session', ['session_id'], ['id'], ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invites', type_='foreignkey')
    op.create_foreign_key(u'invites_session_id_fkey', 'invites', 'session', ['session_id'], ['id'])
    ### end Alembic commands ###
