"""empty message

Revision ID: 6093d5e52b01
Revises: 509a234a3c86
Create Date: 2016-10-15 18:53:48.447385

"""

# revision identifiers, used by Alembic.
revision = '6093d5e52b01'
down_revision = '509a234a3c86'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discount_codes', sa.Column('marketer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'discount_codes', 'user', ['marketer_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'discount_codes', type_='foreignkey')
    op.drop_column('discount_codes', 'marketer_id')
    ### end Alembic commands ###
