"""empty message

Revision ID: 6440077182f0
Revises: eaa029ebb260
Create Date: 2018-06-12 16:12:06.233030

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6440077182f0'
down_revision = 'eaa029ebb260'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('auto_checkin_enabled', sa.Boolean(), nullable=True))
    op.add_column('tickets', sa.Column('is_checkin_restricted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'is_checkin_restricted')
    op.drop_column('tickets', 'auto_checkin_enabled')
    # ### end Alembic commands ###
