"""empty message

Revision ID: 6bd24e8f99f0
Revises: 76c949b1235f
Create Date: 2017-06-21 20:05:08.127436

"""

# revision identifiers, used by Alembic.
revision = '6bd24e8f99f0'
down_revision = '76c949b1235f'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.add_column(u'events', sa.Column('event_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events', 'event_types', ['event_type_id'], ['id'], ondelete='CASCADE')
    op.add_column(u'events_version', sa.Column('event_type_id', sa.Integer(), autoincrement=False, nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'events_version', 'event_type_id')
    op.add_column(u'events', sa.Column('has_sessions_speakers', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column(u'events', 'event_type_id')
    op.drop_table('event_types')
    ### end Alembic commands ###
