"""empty message

Revision ID: 6c2ee19dee3b
Revises: ab545d15d160
Create Date: 2016-07-08 18:23:10.658925

"""

# revision identifiers, used by Alembic.
revision = '6c2ee19dee3b'
down_revision = 'ab545d15d160'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('organizer_url', sa.String(), nullable=True))
    op.add_column('events_version', sa.Column('organizer_url', sa.String(), autoincrement=False, nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events_version', 'organizer_url')
    op.drop_column('events', 'organizer_url')
    ### end Alembic commands ###
