"""Add can_pay_by_omise in event model

Revision ID: 6f7b6fad3f53
Revises: a0532f339abb
Create Date: 2019-05-07 16:14:57.129985

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '6f7b6fad3f53'
down_revision = 'a0532f339abb'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('can_pay_by_omise', sa.Boolean(), nullable=True))
    op.add_column('events_version', sa.Column('can_pay_by_omise', sa.Boolean(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events_version', 'can_pay_by_omise')
    op.drop_column('events', 'can_pay_by_omise')
    # ### end Alembic commands ###
