"""empty message

Revision ID: 6ffaeab2c3c2
Revises: 0d995bfb3671
Create Date: 2017-08-27 16:05:20.575622

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ffaeab2c3c2'
down_revision = '0d995bfb3671'


def upgrade():
    # commands auto generated by Alembic - please adjust! #
    op.add_column('ticket_holders', sa.Column('checkin_times', sa.String(), nullable=True))
    # end Alembic commands #


def downgrade():
    # commands auto generated by Alembic - please adjust! #
    op.drop_column('ticket_holders', 'checkin_times')
    # end Alembic commands #
