"""empty message

Revision ID: 703eda37e75c
Revises: 86fe7df8dca6
Create Date: 2016-08-07 15:11:55.493400

"""

# revision identifiers, used by Alembic.
revision = '703eda37e75c'
down_revision = '86fe7df8dca6'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('pay_by_bank', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('pay_by_cheque', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('pay_by_paypal', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('pay_by_stripe', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('pay_onsite', sa.Boolean(), nullable=True))
    op.add_column('events_version', sa.Column('pay_by_bank', sa.Boolean(), autoincrement=False, nullable=True))
    op.add_column('events_version', sa.Column('pay_by_cheque', sa.Boolean(), autoincrement=False, nullable=True))
    op.add_column('events_version', sa.Column('pay_by_paypal', sa.Boolean(), autoincrement=False, nullable=True))
    op.add_column('events_version', sa.Column('pay_by_stripe', sa.Boolean(), autoincrement=False, nullable=True))
    op.add_column('events_version', sa.Column('pay_onsite', sa.Boolean(), autoincrement=False, nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events_version', 'pay_onsite')
    op.drop_column('events_version', 'pay_by_stripe')
    op.drop_column('events_version', 'pay_by_paypal')
    op.drop_column('events_version', 'pay_by_cheque')
    op.drop_column('events_version', 'pay_by_bank')
    op.drop_column('events', 'pay_onsite')
    op.drop_column('events', 'pay_by_stripe')
    op.drop_column('events', 'pay_by_paypal')
    op.drop_column('events', 'pay_by_cheque')
    op.drop_column('events', 'pay_by_bank')
    ### end Alembic commands ###
