"""empty message

Revision ID: 715b1189ecbd
Revises: a643eb3f2bb4
Create Date: 2016-08-22 20:15:46.150000

"""

# revision identifiers, used by Alembic.
revision = '715b1189ecbd'
down_revision = 'a643eb3f2bb4'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_holders', sa.Column('firstname', sa.String(), nullable=True))
    op.add_column('ticket_holders', sa.Column('lastname', sa.String(), nullable=True))
    op.drop_column('ticket_holders', 'name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_holders', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('ticket_holders', 'lastname')
    op.drop_column('ticket_holders', 'firstname')
    ### end Alembic commands ###
