"""empty message

Revision ID: 752be2444e8d
Revises: ffa958a14ea8
Create Date: 2016-07-28 23:18:47.545000

"""

# revision identifiers, used by Alembic.
revision = '752be2444e8d'
down_revision = 'ffa958a14ea8'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders_tickets',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'ticket_id')
    )
    op.drop_constraint(u'orders_ticket_id_fkey', 'orders', type_='foreignkey')
    op.drop_column(u'orders', 'ticket_id')
    op.drop_column(u'orders', 'quantity')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'orders', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column(u'orders', sa.Column('ticket_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'orders_ticket_id_fkey', 'orders', 'ticket', ['ticket_id'], ['id'])
    op.drop_table('orders_tickets')
    ### end Alembic commands ###
