"""empty message

Revision ID: 76617aa50e25
Revises: 81a713eded64
Create Date: 2017-01-13 21:08:29.619807

"""

# revision identifiers, used by Alembic.
revision = '76617aa50e25'
down_revision = '81a713eded64'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('tagline', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'tagline')
    ### end Alembic commands ###
