"""empty message

Revision ID: 784a1fc57171
Revises: 523742f2b632
Create Date: 2016-06-15 23:17:34.048000

"""

# revision identifiers, used by Alembic.
revision = '784a1fc57171'
down_revision = '523742f2b632'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('privacy', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'privacy')
    ### end Alembic commands ###
