"""empty message

Revision ID: 79e54124b415
Revises: affad812c947
Create Date: 2016-08-29 12:08:14.717319

"""

# revision identifiers, used by Alembic.
revision = '79e54124b415'
down_revision = 'affad812c947'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('speaker', sa.Column('icon', sa.String(), nullable=True))
    op.add_column('speaker', sa.Column('small', sa.String(), nullable=True))
    op.add_column('speaker', sa.Column('thumbnail', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('speaker', 'thumbnail')
    op.drop_column('speaker', 'small')
    op.drop_column('speaker', 'icon')
    ### end Alembic commands ###
