"""empty message

Revision ID: 7cf31ed98b0c
Revises: faf2cd17a4f4
Create Date: 2016-07-28 04:45:53.227633

"""

# revision identifiers, used by Alembic.
revision = '7cf31ed98b0c'
down_revision = 'faf2cd17a4f4'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('payment_country', sa.String(), nullable=True))
    op.add_column('events', sa.Column('payment_currency', sa.String(), nullable=True))
    op.add_column('events_version', sa.Column('payment_country', sa.String(), autoincrement=False, nullable=True))
    op.add_column('events_version', sa.Column('payment_currency', sa.String(), autoincrement=False, nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events_version', 'payment_currency')
    op.drop_column('events_version', 'payment_country')
    op.drop_column('events', 'payment_currency')
    op.drop_column('events', 'payment_country')
    ### end Alembic commands ###
