"""empty message

Revision ID: 80d2754fb939
Revises: 60548d0505ea
Create Date: 2016-11-19 19:12:11.178836

"""

# revision identifiers, used by Alembic.
revision = '80d2754fb939'
down_revision = '60548d0505ea'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('gs_bucket_name', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('gs_key', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('gs_secret', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'gs_secret')
    op.drop_column('settings', 'gs_key')
    op.drop_column('settings', 'gs_bucket_name')
    ### end Alembic commands ###
