"""empty message

Revision ID: 82ae4cf20ae9
Revises: 91ee86a38001
Create Date: 2019-02-10 17:40:43.244583

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82ae4cf20ae9'
down_revision = '91ee86a38001'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_twitter_id_key', 'users', type_='unique')
    op.drop_column('users', 'twitter_id')
    op.drop_column('users', 'twitter_login_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('twitter_login_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('twitter_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_twitter_id_key', 'users', ['twitter_id'])
    # ### end Alembic commands ###
