"""empty message

Revision ID: 8500f5ec6c45
Revises: e85aaacd8721
Create Date: 2017-07-13 02:26:39.135397

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '8500f5ec6c45'
down_revision = 'bf559a01a63b'

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('original_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'original_image_url')
    # ### end Alembic commands ###
