"""empty message

Revision ID: 91ee86a38001
Revises: 41818fe31207
Create Date: 2019-01-25 13:40:31.819688

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91ee86a38001'
down_revision = 'e3caa0f2a16c'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('company', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('tax_business_info', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'tax_business_info')
    op.drop_column('orders', 'company')
    # ### end Alembic commands ###
