"""empty message

Revision ID: 92d65554495c
Revises: 86fe7df8dca6
Create Date: 2016-08-07 13:04:13.289000

"""

# revision identifiers, used by Alembic.
revision = '92d65554495c'
down_revision = '86fe7df8dca6'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('paypal_live_password', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('paypal_live_signature', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('paypal_live_username', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('paypal_mode', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('paypal_sandbox_password', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('paypal_sandbox_signature', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('paypal_sandbox_username', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'paypal_sandbox_username')
    op.drop_column('settings', 'paypal_sandbox_signature')
    op.drop_column('settings', 'paypal_sandbox_password')
    op.drop_column('settings', 'paypal_mode')
    op.drop_column('settings', 'paypal_live_username')
    op.drop_column('settings', 'paypal_live_signature')
    op.drop_column('settings', 'paypal_live_password')
    ### end Alembic commands ###
