"""empty message

Revision ID: 94e639e6575c
Revises: dd97b5e8fa6b
Create Date: 2016-12-31 16:45:34.133509

"""

# revision identifiers, used by Alembic.
revision = '94e639e6575c'
down_revision = 'dd97b5e8fa6b'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('speaker', 'level')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('speaker', sa.Column('level', sa.VARCHAR(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
