"""empty message

Revision ID: 98166ca15055
Revises: dbb79ff12e45
Create Date: 2016-05-23 13:05:50.163693

"""

# revision identifiers, used by Alembic.
revision = '98166ca15055'
down_revision = 'dbb79ff12e45'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_link',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('link', sa.String(), nullable=False),
                    sa.Column('event_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('social_link')
    ### end Alembic commands ###
