"""empty message

Revision ID: 98c151c7a16a
Revises: ffbb4d4dad39
Create Date: 2016-06-29 11:17:49.298442

"""

# revision identifiers, used by Alembic.
revision = '98c151c7a16a'
down_revision = 'ffbb4d4dad39'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('sub_topic', sa.String(), nullable=True))
    op.add_column('events_version', sa.Column('sub_topic', sa.String(), autoincrement=False, nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events_version', 'sub_topic')
    op.drop_column('events', 'sub_topic')
    ### end Alembic commands ###
