"""empty message

Revision ID: 9913b58c2640
Revises: ddc941500bd2
Create Date: 2016-07-29 23:23:27.324000

"""

# revision identifiers, used by Alembic.
revision = '9913b58c2640'
down_revision = 'ddc941500bd2'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('brand', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('exp_month', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('exp_year', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('last4', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('payment_mode', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_mode')
    op.drop_column('orders', 'last4')
    op.drop_column('orders', 'exp_year')
    op.drop_column('orders', 'exp_month')
    op.drop_column('orders', 'brand')
    ### end Alembic commands ###
