"""empty message

Revision ID: 9b1050b22e9d
Revises: 5bff18b52910
Create Date: 2016-06-29 23:17:32.495000

"""

# revision identifiers, used by Alembic.
revision = '9b1050b22e9d'
down_revision = '5bff18b52910'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events_version', sa.Column('in_trash', sa.Boolean(), autoincrement=False, nullable=True))
    op.add_column('session_version', sa.Column('in_trash', sa.Boolean(), autoincrement=False, nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_version', 'in_trash')
    op.drop_column('events_version', 'in_trash')
    ### end Alembic commands ###
