"""empty message

Revision ID: 9e1204b2e096
Revises: 740b89e12cbb
Create Date: 2017-07-08 16:17:25.238307

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e1204b2e096'
down_revision = '740b89e12cbb'


def upgrade():
    # commands auto generated by Alembic - please adjust! #
    op.execute("DELETE FROM role_invites WHERE email='' ",
               execution_options=None)
    op.alter_column('role_invites', 'email',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('role_invites', 'is_declined', new_column_name='status')
    op.execute("ALTER TABLE role_invites ALTER status TYPE varchar USING CASE status WHEN TRUE THEN 'declined'\
                ELSE 'pending' END", execution_options=None)
    # end Alembic commands #


def downgrade():
    # commands auto generated by Alembic - please adjust! #
    op.alter_column('role_invites', 'email',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.execute("ALTER TABLE role_invites ALTER status TYPE boolean USING CASE status WHEN 'declined' THEN TRUE\
                ELSE FALSE END", execution_options=None)
    op.alter_column('role_invites', 'status', new_column_name='is_declined')
    # end Alembic commands #
