"""empty message

Revision ID: 9eb4b61d0acb
Revises: 6153d21347b9
Create Date: 2016-06-25 23:30:45.180000

"""

# revision identifiers, used by Alembic.
revision = '9eb4b61d0acb'
down_revision = '6153d21347b9'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), autoincrement=False, nullable=True),
    sa.Column('email', sa.String(), autoincrement=False, nullable=True),
    sa.Column('color', sqlalchemy_utils.types.color.ColorType(length=20), autoincrement=False, nullable=True),
    sa.Column('logo', sa.String(), autoincrement=False, nullable=True),
    sa.Column('start_time', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('end_time', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('timezone', sa.String(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('location_name', sa.String(), autoincrement=False, nullable=True),
    sa.Column('description', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('event_url', sa.String(), autoincrement=False, nullable=True),
    sa.Column('background_url', sa.String(), autoincrement=False, nullable=True),
    sa.Column('organizer_name', sa.String(), autoincrement=False, nullable=True),
    sa.Column('organizer_description', sa.String(), autoincrement=False, nullable=True),
    sa.Column('privacy', sa.String(), autoincrement=False, nullable=True),
    sa.Column('state', sa.String(), autoincrement=False, nullable=True),
    sa.Column('closing_datetime', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('type', sa.String(), autoincrement=False, nullable=True),
    sa.Column('topic', sa.String(), autoincrement=False, nullable=True),
    sa.Column('ticket_url', sa.String(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_events_version_operation_type'), 'events_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_events_version_transaction_id'), 'events_version', ['transaction_id'], unique=False)
    op.create_table('session_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('title', sa.String(), autoincrement=False, nullable=True),
    sa.Column('subtitle', sa.String(), autoincrement=False, nullable=True),
    sa.Column('short_abstract', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('long_abstract', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('comments', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('start_time', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('end_time', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('track_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('language', sa.String(), autoincrement=False, nullable=True),
    sa.Column('microlocation_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('session_type_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('slides', sa.String(), autoincrement=False, nullable=True),
    sa.Column('video', sa.String(), autoincrement=False, nullable=True),
    sa.Column('audio', sa.String(), autoincrement=False, nullable=True),
    sa.Column('signup_url', sa.String(), autoincrement=False, nullable=True),
    sa.Column('event_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('state', sa.String(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_session_version_operation_type'), 'session_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_session_version_transaction_id'), 'session_version', ['transaction_id'], unique=False)
    op.create_table('speakers_sessions_version',
    sa.Column('speaker_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_speakers_sessions_version_operation_type'), 'speakers_sessions_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_speakers_sessions_version_transaction_id'), 'speakers_sessions_version', ['transaction_id'], unique=False)
    op.create_table('transaction',
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('remote_addr', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_user_id'), 'transaction', ['user_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_user_id'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_speakers_sessions_version_transaction_id'), table_name='speakers_sessions_version')
    op.drop_index(op.f('ix_speakers_sessions_version_operation_type'), table_name='speakers_sessions_version')
    op.drop_table('speakers_sessions_version')
    op.drop_index(op.f('ix_session_version_transaction_id'), table_name='session_version')
    op.drop_index(op.f('ix_session_version_operation_type'), table_name='session_version')
    op.drop_table('session_version')
    op.drop_index(op.f('ix_events_version_transaction_id'), table_name='events_version')
    op.drop_index(op.f('ix_events_version_operation_type'), table_name='events_version')
    op.drop_table('events_version')
    ### end Alembic commands ###
