"""empty message

Revision ID: a48b4f13c561
Revises: 9a01232a22cc
Create Date: 2016-06-10 16:13:17.828021

"""

# revision identifiers, used by Alembic.
revision = 'a48b4f13c561'
down_revision = '9a01232a22cc'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sponsor_type', sa.Column('event_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sponsor_type', 'events', ['event_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sponsor_type', type_='foreignkey')
    op.drop_column('sponsor_type', 'event_id')
    ### end Alembic commands ###
