"""empty message

Revision ID: a6e5abbcc205
Revises: 89a5b836b406
Create Date: 2019-06-09 10:36:35.767080

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'a6e5abbcc205'
down_revision = '89a5b836b406'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('country_currency_uc', 'ticket_fees', ['currency', 'country'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('country_currency_uc', 'ticket_fees', type_='unique')
    # ### end Alembic commands ###
