"""empty message

Revision ID: a71a8fcf6493
Revises: c79e6d36a194
Create Date: 2017-06-16 22:57:31.042325

"""

# revision identifiers, used by Alembic.
revision = 'a71a8fcf6493'
down_revision = 'c79e6d36a194'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'track_image_url')
    op.drop_column('tracks', 'location')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tracks', sa.Column('track_image_url', sa.TEXT(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
