"""empty message

Revision ID: a79f1dc2fd67
Revises: ae95fb82282d
Create Date: 2018-06-27 02:16:18.148115

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a79f1dc2fd67'
down_revision = 'ae95fb82282d'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_types', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('social_links', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('stripe_authorizations', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_links', 'deleted_at')
    op.drop_column('session_types', 'deleted_at')
    op.drop_column('stripe_authorizations', 'deleted_at')
    # ### end Alembic commands ###
