"""empty message

Revision ID: aa204a8b5743
Revises: 90a9f0908326
Create Date: 2016-08-18 23:47:48.760843

"""

# revision identifiers, used by Alembic.
revision = 'aa204a8b5743'
down_revision = '90a9f0908326'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_placeholder', sa.Column('thumbnail', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_placeholder', 'thumbnail')
    ### end Alembic commands ###
