"""empty message

Revision ID: abe953265132
Revises: af9215895b80
Create Date: 2017-06-13 21:46:19.772583

"""

# revision identifiers, used by Alembic.
revision = 'abe953265132'
down_revision = 'af9215895b80'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('call_for_papers', 'speakers_calls')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('speakers_calls', 'call_for_papers')
    # ### end Alembic commands ###
