"""empty message

Revision ID: ac2a9daf5a8e
Revises: f0c5ef58ad19
Create Date: 2016-12-05 19:55:32.893709

"""

# revision identifiers, used by Alembic.
revision = 'ac2a9daf5a8e'
down_revision = 'f0c5ef58ad19'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('aws_region', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'aws_region')
    ### end Alembic commands ###
