"""empty message

Revision ID: affad812c947
Revises: 81fe5a689259
Create Date: 2016-08-27 12:03:49.365856

"""

# revision identifiers, used by Alembic.
revision = 'affad812c947'
down_revision = '81fe5a689259'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_detail', sa.Column('icon', sa.String(), nullable=True))
    op.add_column('user_detail', sa.Column('small', sa.String(), nullable=True))
    op.add_column('user_detail', sa.Column('thumbnail', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_detail', 'thumbnail')
    op.drop_column('user_detail', 'small')
    op.drop_column('user_detail', 'icon')
    ### end Alembic commands ###
