"""empty message

Revision ID: b15e124e9b93
Revises: 38f11aa39bff
Create Date: 2017-06-06 17:43:06.302985

"""

# revision identifiers, used by Alembic.
revision = 'b15e124e9b93'
down_revision = '38f11aa39bff'

from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'submission_date', new_column_name='submitted_at')
    op.alter_column('sessions_version', 'submission_date', new_column_name='submitted_at')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'submitted_at', new_column_name='submission_date')
    op.alter_column('sessions_version', 'submitted_at', new_column_name='submission_date')
    ### end Alembic commands ###
