"""empty message

Revision ID: b20ae211b8e0
Revises: c1bc95d0d654
Create Date: 2016-06-23 04:38:19.982708

"""

# revision identifiers, used by Alembic.
revision = 'b20ae211b8e0'
down_revision = 'c1bc95d0d654'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('name_event_uc', 'ticket', ['name', 'event_id'])
    op.drop_constraint(u'ticket_name_key', 'ticket', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'ticket_name_key', 'ticket', ['name'])
    op.drop_constraint('name_event_uc', 'ticket', type_='unique')
    ### end Alembic commands ###
