"""empty message

Revision ID: b3bfa7949acf
Revises: 6f7b6fad3f55
Create Date: 2019-05-20 04:52:51.103580

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'b3bfa7949acf'
down_revision = '6f7b6fad3f55'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('is_locked', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('sessions_version', sa.Column('is_locked', sa.Boolean(), server_default='False', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions_version', 'is_locked')
    op.drop_column('sessions', 'is_locked')
    # ### end Alembic commands ###
