"""empty message

Revision ID: b4fdb245fccd
Revises: 4c7f86bbed3d
Create Date: 2017-08-22 13:38:37.526669

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'b4fdb245fccd'
down_revision = '4c7f86bbed3d'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_holders', sa.Column('billing_address', sa.String(), nullable=True))
    op.add_column('ticket_holders', sa.Column('birth_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ticket_holders', sa.Column('blog', sa.String(), nullable=True))
    op.add_column('ticket_holders', sa.Column('company', sa.String(), nullable=True))
    op.add_column('ticket_holders', sa.Column('facebook', sa.String(), nullable=True))
    op.add_column('ticket_holders', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('ticket_holders', sa.Column('github', sa.String(), nullable=True))
    op.add_column('ticket_holders', sa.Column('home_address', sa.String(), nullable=True))
    op.add_column('ticket_holders', sa.Column('job_title', sa.String(), nullable=True))
    op.add_column('ticket_holders', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('ticket_holders', sa.Column('shipping_address', sa.String(), nullable=True))
    op.add_column('ticket_holders', sa.Column('tax_business_info', sa.String(), nullable=True))
    op.add_column('ticket_holders', sa.Column('twitter', sa.String(), nullable=True))
    op.add_column('ticket_holders', sa.Column('website', sa.String(), nullable=True))
    op.add_column('ticket_holders', sa.Column('work_address', sa.String(), nullable=True))
    op.add_column('ticket_holders', sa.Column('work_phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_holders', 'work_phone')
    op.drop_column('ticket_holders', 'work_address')
    op.drop_column('ticket_holders', 'website')
    op.drop_column('ticket_holders', 'twitter')
    op.drop_column('ticket_holders', 'tax_business_info')
    op.drop_column('ticket_holders', 'shipping_address')
    op.drop_column('ticket_holders', 'phone')
    op.drop_column('ticket_holders', 'job_title')
    op.drop_column('ticket_holders', 'home_address')
    op.drop_column('ticket_holders', 'github')
    op.drop_column('ticket_holders', 'gender')
    op.drop_column('ticket_holders', 'facebook')
    op.drop_column('ticket_holders', 'company')
    op.drop_column('ticket_holders', 'blog')
    op.drop_column('ticket_holders', 'birth_date')
    op.drop_column('ticket_holders', 'billing_address')
    # ### end Alembic commands ###
