"""empty message

Revision ID: b54b31013604
Revises: 3ca4aedaa7df
Create Date: 2018-07-27 12:25:41.282164

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b54b31013604'
down_revision = '3ca4aedaa7df'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_actions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('action_type', sa.String(), nullable=True),
        sa.Column('subject', sa.String(), nullable=True),
        sa.Column('notification_topic', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column('notifications', sa.Column('notification_topic', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.drop_column('notifications', 'action')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('notifications', 'subject_id')
    op.drop_column('notifications', 'notification_topic')
    op.drop_table('notification_actions')
    # ### end Alembic commands ###
