"""empty message

Revision ID: b5abafa45063
Revises: 4e5dd0df14b5
Create Date: 2016-08-06 22:29:36.948000

"""

# revision identifiers, used by Alembic.
revision = 'b5abafa45063'
down_revision = '4e5dd0df14b5'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_authorizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stripe_secret_key', sa.String(), nullable=True),
    sa.Column('stripe_refresh_token', sa.String(), nullable=True),
    sa.Column('stripe_publishable_key', sa.String(), nullable=True),
    sa.Column('stripe_user_id', sa.String(), nullable=True),
    sa.Column('stripe_email', sa.String(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stripe_authorizations')
    ### end Alembic commands ###
