"""empty message

Revision ID: b723e2342f15
Revises: 26a83ff1e6ad
Create Date: 2016-06-17 03:31:11.246151

"""

# revision identifiers, used by Alembic.
revision = 'b723e2342f15'
down_revision = '26a83ff1e6ad'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('language', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'language')
    ### end Alembic commands ###
