"""empty message

Revision ID: b79853132e71
Revises: 715b1189ecbd
Create Date: 2016-08-22 20:27:28.567000

"""

# revision identifiers, used by Alembic.
revision = 'b79853132e71'
down_revision = '715b1189ecbd'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_holders', sa.Column('ticket_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ticket_holders', 'ticket', ['ticket_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ticket_holders', type_='foreignkey')
    op.drop_column('ticket_holders', 'ticket_id')
    ### end Alembic commands ###
