"""empty message

Revision ID: ba9307b2eb82
Revises: 848f6f918b3d
Create Date: 2016-07-25 14:49:48.688366

"""

# revision identifiers, used by Alembic.
revision = 'ba9307b2eb82'
down_revision = '848f6f918b3d'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('server_name', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'server_name')
    ### end Alembic commands ###
