"""empty message

Revision ID: bae57b0ae2cd
Revises: b15e124e9b93
Create Date: 2017-06-09 19:53:06.956314

"""

# revision identifiers, used by Alembic.
revision = 'bae57b0ae2cd'
down_revision = 'b15e124e9b93'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tax','is_invoice_sent',new_column_name='should_send_invoice')
    op.alter_column('tax','tax_name',new_column_name='name')
    op.alter_column('tax','tax_rate',new_column_name='rate')
    op.alter_column('tickets','sales_start',new_column_name='sales_starts_at')
    op.alter_column('tickets','sales_end',new_column_name='sales_ends_at')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tax','should_send_invoice',new_column_name='is_invoice_sent')
    op.alter_column('tax','name',new_column_name='tax_name')
    op.alter_column('tax','rate',new_column_name='tax_rate')
    op.alter_column('tickets','sales_starts_at',new_column_name='sales_start')
    op.alter_column('tickets','sales_ends_at',new_column_name='sales_end')
    ### end Alembic commands ###
