"""empty message

Revision ID: bc6757b5bb64
Revises: 91ee86a38001
Create Date: 2019-02-09 21:56:45.168459

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'bc6757b5bb64'
down_revision = '91ee86a38001'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('github_client_id', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('github_client_secret', sa.String(), nullable=True))
    op.add_column('users', sa.Column('github_id', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('github_login_hash', sa.String(), nullable=True))
    op.create_unique_constraint('github_id_unique', 'users', ['github_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('github_id_unique', 'users', type_='unique')
    op.drop_column('users', 'github_login_hash')
    op.drop_column('users', 'github_id')
    op.drop_column('settings', 'github_client_secret')
    op.drop_column('settings', 'github_client_id')
    # ### end Alembic commands ###
