"""empty message

Revision ID: bf3e8c2a01f6
Revises: dbb9670cd902
Create Date: 2017-08-08 17:09:52.402284

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from sqlalchemy import engine_from_config

# revision identifiers, used by Alembic.
revision = 'bf3e8c2a01f6'
down_revision = 'dbb9670cd902'


def table_exists(table):
    config = op.get_context().config
    engine = engine_from_config(
        config.get_section(config.config_ini_section), prefix='sqlalchemy.')
    return engine.dialect.has_table(engine, table)


def upgrade():
    # commands auto generated by Alembic - please adjust! #
    pass
    # end Alembic commands #


def downgrade():
    # commands auto generated by Alembic - please adjust! #
    pass
    # end Alembic commands #
