"""empty message

Revision ID: bf894430e0a9
Revises: 5b37561a6d2b
Create Date: 2016-06-27 12:50:52.732000

"""

# revision identifiers, used by Alembic.
revision = 'bf894430e0a9'
down_revision = '5b37561a6d2b'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('session_version', sa.Column('created_at', sa.DateTime(), autoincrement=False, nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_version', 'created_at')
    op.drop_column('session', 'created_at')
    ### end Alembic commands ###
