"""empty message

Revision ID: c5fc44dd6653
Revises: a9da7e8e763b
Create Date: 2017-07-19 12:13:28.250129

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c5fc44dd6653'
down_revision = 'f94439299737'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_holders', sa.Column('event_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ticket_holders', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ticket_holders', type_='foreignkey')
    op.drop_column('ticket_holders', 'event_id')
    # ### end Alembic commands ###
