"""empty message

Revision ID: c79e6d36a194
Revises: af9215895b80
Create Date: 2017-06-16 12:37:11.548426

"""

# revision identifiers, used by Alembic.
revision = 'c79e6d36a194'
down_revision = 'af9215895b80'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar', new_column_name='avatar_url')
    op.alter_column('users', 'facebook', new_column_name='facebook_url')
    op.alter_column('users', 'firstname', new_column_name='first_name')
    op.alter_column('users', 'google', new_column_name='google_plus_url')
    op.alter_column('users', 'icon', new_column_name='icon_image_url')
    op.alter_column('users', 'instagram', new_column_name='instagram_url')
    op.alter_column('users', 'lastname', new_column_name='last_name')
    op.alter_column('users', 'small', new_column_name='small_image_url')
    op.alter_column('users', 'thumbnail', new_column_name='thumbnail_image_url')
    op.alter_column('users', 'twitter', new_column_name='twitter_url')
    op.drop_column('users', 'signup_at')
    op.drop_column('users', 'avatar_uploaded')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_uploaded',
                                     sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('signup_at', postgresql.TIMESTAMP(
        timezone=True), autoincrement=False, nullable=True))
    op.alter_column('users', 'twitter_url', new_column_name='twitter')
    op.alter_column('users', 'thumbnail_image_url', new_column_name='thumbnail')
    op.alter_column('users', 'small_image_url', new_column_name='small')
    op.alter_column('users', 'last_name', new_column_name='lastname')
    op.alter_column('users', 'instagram_url', new_column_name='instagram')
    op.alter_column('users', 'icon_image_url', new_column_name='icon')
    op.alter_column('users', 'google_plus_url', new_column_name='google')
    op.alter_column('users', 'first_name', new_column_name='firstname')
    op.alter_column('users', 'facebook_url', new_column_name='facebook')
    op.alter_column('users', 'avatar_url', new_column_name='avatar')
    ### end Alembic commands ###
