"""empty message

Revision ID: c87273102cfb
Revises: 217c21289729
Create Date: 2016-06-16 16:56:05.302225

"""

# revision identifiers, used by Alembic.
revision = 'c87273102cfb'
down_revision = '217c21289729'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'session_level_id_fkey', 'session', type_='foreignkey')
    op.drop_table('level')
    op.drop_column('session', 'level_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('level_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'session_level_id_fkey', 'session', 'level', ['level_id'], ['id'])
    op.create_table('level',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('label_en', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'level_pkey')
    )
    ### end Alembic commands ###
