"""empty message

Revision ID: cb4ccda76a2b
Revises: 0e80c49a6e28
Create Date: 2019-06-03 22:57:01.500527

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'cb4ccda76a2b'
down_revision = '0e80c49a6e28'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'ticket_fees', ['country'])
    op.create_unique_constraint(None, 'ticket_fees', ['currency'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ticket_fees', type_='unique')
    op.drop_constraint(None, 'ticket_fees', type_='unique')
    # ### end Alembic commands ###
