"""empty message

Revision ID: ce0b8ccd98ce
Revises: a5f2c19b7ac9
Create Date: 2017-01-18 01:56:58.497552

"""

# revision identifiers, used by Alembic.
revision = 'ce0b8ccd98ce'
down_revision = 'a5f2c19b7ac9'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_notification', sa.Column('after_ticket_purchase', sa.Integer(), nullable=True))
    op.execute('UPDATE email_notification SET after_ticket_purchase = 1 WHERE after_ticket_purchase is NULL ', execution_options=None)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_notification', 'after_ticket_purchase')
    ### end Alembic commands ###
