"""empty message

Revision ID: cfe06645c991
Revises: df468100bb57
Create Date: 2018-07-21 09:14:44.196756

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfe06645c991'
down_revision = 'df468100bb57'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('tickets_pdf_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'tickets_pdf_url')
    # ### end Alembic commands ###
