"""empty message

Revision ID: d3fa4a1dbb8f
Revises: a946e9a677e1
Create Date: 2016-06-24 20:20:19.144516

"""

# revision identifiers, used by Alembic.
revision = 'd3fa4a1dbb8f'
down_revision = 'a946e9a677e1'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_notification', 'next_event')
    op.drop_column('email_notification', 'new_paper')
    op.drop_column('email_notification', 'session_accept_reject')
    op.drop_column('email_notification', 'session_schedule')
    op.add_column('email_notification', sa.Column('next_event', sa.Integer(), nullable=True))
    op.add_column('email_notification', sa.Column('new_paper', sa.Integer(), nullable=True))
    op.add_column('email_notification', sa.Column('session_accept_reject', sa.Integer(), nullable=True))
    op.add_column('email_notification', sa.Column('session_schedule', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_notification', 'next_event')
    op.drop_column('email_notification', 'new_paper')
    op.drop_column('email_notification', 'session_accept_reject')
    op.drop_column('email_notification', 'session_schedule')
    op.add_column('email_notification', sa.Column('next_event', sa.Binary(), nullable=True))
    op.add_column('email_notification', sa.Column('new_paper', sa.Binary(), nullable=True))
    op.add_column('email_notification', sa.Column('session_accept_reject', sa.Binary(), nullable=True))
    op.add_column('email_notification', sa.Column('session_schedule', sa.Binary(), nullable=True))
    ### end Alembic commands ###
