"""empty message

Revision ID: d6466bfab14b
Revises: e3caa0f2a16c
Create Date: 2019-02-02 13:17:52.104761

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6466bfab14b'
down_revision = 'e3caa0f2a16c'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events',
                  sa.Column('is_featured', 
                            sa.Boolean(),
                            server_default='False',
                            nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'is_featured')
    # ### end Alembic commands ###
