"""empty message

Revision ID: dcc03295ba71
Revises: 591df081093e
Create Date: 2016-06-15 20:07:34.358000

"""

# revision identifiers, used by Alembic.
revision = 'dcc03295ba71'
down_revision = '591df081093e'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session', 'abstract', new_column_name='short_abstract')
    op.alter_column('session', 'description', new_column_name='long_abstract')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session', 'short_abstract', new_column_name='abstract')
    op.alter_column('session', 'long_abstract', new_column_name='description')
    ### end Alembic commands ###
