"""empty message

Revision ID: ddaa6df27340
Revises: d763cf2e7dc4
Create Date: 2017-05-12 15:20:05.928181

"""

# revision identifiers, used by Alembic.
revision = 'ddaa6df27340'
down_revision = 'd763cf2e7dc4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('sponsors_enabled', sa.Boolean(), server_default=sa.schema.DefaultClause("0"), nullable=True))
    op.add_column('events_version', sa.Column('sponsors_enabled', sa.Boolean(), server_default=sa.schema.DefaultClause("0"), autoincrement=False, nullable=True))
    op.execute('UPDATE events as e SET sponsors_enabled=TRUE FROM sponsors AS s WHERE e.id = s.event_id ',
               execution_options=None)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events_version', 'sponsors_enabled')
    op.drop_column('events', 'sponsors_enabled')
    ### end Alembic commands ###
