"""empty message

Revision ID: df5729aed5d2
Revises: 3ddac4799fb1
Create Date: 2016-06-17 11:41:46.306817

"""

# revision identifiers, used by Alembic.
revision = 'df5729aed5d2'
down_revision = '3ddac4799fb1'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    ### end Alembic commands ###
