"""empty message
Revision ID: e20a821c7c7e
Revises: 91ee86a38001
Create Date: 2019-02-10 17:43:09.014532
"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'e20a821c7c7e'
down_revision = '91ee86a38001'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('twitter_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('twitter_login_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'twitter_login_hash')
    op.drop_column('users', 'twitter_id')
    # ### end Alembic commands ###
