"""empty message

Revision ID: e385c8e1368a
Revises: 7a110ca7061b
Create Date: 2016-06-15 14:55:39.007510

"""

# revision identifiers, used by Alembic.
revision = 'e385c8e1368a'
down_revision = '7a110ca7061b'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('audio', sa.String(), nullable=True))
    op.add_column('session', sa.Column('signup_url', sa.String(), nullable=True))
    op.add_column('session', sa.Column('slides', sa.String(), nullable=True))
    op.add_column('session', sa.Column('video', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'video')
    op.drop_column('session', 'slides')
    op.drop_column('session', 'signup_url')
    op.drop_column('session', 'audio')
    ### end Alembic commands ###
