"""empty message

Revision ID: e85aaacd8721
Revises: ad789015cdf7
Create Date: 2017-07-10 20:33:41.743320

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'e85aaacd8721'
down_revision = 'ad789015cdf7'


def upgrade():
    # commands auto generated by Alembic - please adjust! #
    op.add_column('events', sa.Column('discount_code_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events', 'discount_codes', ['discount_code_id'], ['id'], ondelete='CASCADE')
    op.add_column('events_version', sa.Column('discount_code_id', sa.Integer(), autoincrement=False, nullable=True))
    op.execute("DELETE FROM discount_codes WHERE code='' ",
               execution_options=None)
    op.alter_column('discount_codes', 'code',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.execute("DELETE FROM discount_codes WHERE type='' ",
               execution_options=None)
    op.alter_column('discount_codes', 'type',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.execute("DELETE FROM discount_codes WHERE used_for='' ",
               execution_options=None)
    op.alter_column('discount_codes', 'used_for',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.execute("DELETE FROM discount_codes WHERE value is null",
               execution_options=None)
    op.alter_column('discount_codes', 'value',
                    existing_type=postgresql.DOUBLE_PRECISION(precision=53),
                    nullable=False)
    # end Alembic commands #


def downgrade():
    # commands auto generated by Alembic - please adjust! #
    op.drop_column('events_version', 'discount_code_id')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'discount_code_id')
    op.add_column('events', sa.Column('has_sessions_speakers', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('discount_codes', 'value',
                    existing_type=postgresql.DOUBLE_PRECISION(precision=53),
                    nullable=True)
    op.alter_column('discount_codes', 'used_for',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('discount_codes', 'type',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('discount_codes', 'code',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    # end Alembic commands #
