"""empty message

Revision ID: f01ca39e930e
Revises: 0d25e6904746
Create Date: 2016-06-09 08:16:14.667138

"""

# revision identifiers, used by Alembic.
revision = 'f01ca39e930e'
down_revision = '0d25e6904746'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('audio', sa.String(), nullable=True))
    op.add_column('session', sa.Column('signup_url', sa.String(), nullable=True))
    op.add_column('session', sa.Column('slides_url', sa.String(), nullable=True))
    op.add_column('session', sa.Column('video_url', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'video_url')
    op.drop_column('session', 'slides_url')
    op.drop_column('session', 'signup_url')
    op.drop_column('session', 'audio')
    ### end Alembic commands ###
