"""empty message

Revision ID: f07fed8f60e5
Revises: 1552f7bafb5b
Create Date: 2016-06-16 20:54:35.573548

"""

# revision identifiers, used by Alembic.
revision = 'f07fed8f60e5'
down_revision = '1552f7bafb5b'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eventsusers', 'role')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eventsusers', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False))
    ### end Alembic commands ###
