"""empty message

Revision ID: f462f192655a
Revises: 45d3fa90393d
Create Date: 2016-03-20 09:31:16.636204

"""

# revision identifiers, used by Alembic.
revision = 'f462f192655a'
down_revision = '45d3fa90393d'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'_unique_review_id', 'review', type_='unique')
    op.create_unique_constraint('_unique_review_id', 'review', ['email', 'session_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_unique_review_id', 'review', type_='unique')
    op.create_unique_constraint(u'_unique_review_id', 'review', ['id', 'session_id'])
    ### end Alembic commands ###
