"""empty message

Revision ID: f552e3e64bf8
Revises: cfe06645c991
Create Date: 2018-07-21 20:47:15.493654

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f552e3e64bf8'
down_revision = 'cfe06645c991'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('facebook_id', sa.BigInteger(), nullable=True))
    op.create_unique_constraint('facebook_id_unique', 'users', ['facebook_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('facebook_id_unique', 'users', type_='unique')
    op.drop_column('users', 'facebook_id')
    # ### end Alembic commands ###
