"""empty message

Revision ID: f5ad6fb15f50
Revises: 848f6f918b3d
Create Date: 2016-07-26 09:46:29.176136

"""

# revision identifiers, used by Alembic.
revision = 'f5ad6fb15f50'
down_revision = '848f6f918b3d'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('date_of_submission', sa.DateTime(), nullable=True))
    op.add_column('session', sa.Column('submission_modifier', sa.String(), nullable=True))
    op.add_column('session_version', sa.Column('date_of_submission', sa.DateTime(), autoincrement=False, nullable=True))
    op.add_column('session_version', sa.Column('submission_modifier', sa.String(), autoincrement=False, nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_version', 'submission_modifier')
    op.drop_column('session_version', 'date_of_submission')
    op.drop_column('session', 'submission_modifier')
    op.drop_column('session', 'date_of_submission')
    ### end Alembic commands ###
