"""empty message

Revision ID: f5c28956049b
Revises: b08a4ffff5dd
Create Date: 2019-06-24 02:46:54.012871

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'f5c28956049b'
down_revision = 'b08a4ffff5dd'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_forms', sa.Column('is_custom_question', sa.Boolean(), nullable=False, server_default='False'))
    op.add_column('custom_forms', sa.Column('prompt', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_forms', 'prompt')
    op.drop_column('custom_forms', 'is_custom_question')
    # ### end Alembic commands ###
