"""empty message

Revision ID: f6205b904315
Revises: 5155b2a9f3fc
Create Date: 2016-12-31 14:02:28.927938

"""

# revision identifiers, used by Alembic.
revision = 'f6205b904315'
down_revision = '5155b2a9f3fc'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('speaker', sa.Column('city', sa.String(), nullable=True))
    op.add_column('speaker', sa.Column('sponsorship_required', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('speaker', 'sponsorship_required')
    op.drop_column('speaker', 'city')
    ### end Alembic commands ###
