"""empty message

Revision ID: f79764fe536e
Revises: 00ea66754d06
Create Date: 2016-06-14 03:26:04.095775

"""

# revision identifiers, used by Alembic.
revision = 'f79764fe536e'
down_revision = '00ea66754d06'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.alter_column(u'role', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.create_unique_constraint(None, 'role', ['name'])
    op.drop_column(u'user', 'role')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'user', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'role', type_='unique')
    op.alter_column(u'role', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.drop_table('user_roles')
    ### end Alembic commands ###
