"""empty message

Revision ID: f873b99e5be3
Revises: 047f7c3db184
Create Date: 2016-07-15 22:54:20.423244

"""

# revision identifiers, used by Alembic.
revision = 'f873b99e5be3'
down_revision = '047f7c3db184'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('sales_start', sa.DateTime(), nullable=False),
    sa.Column('sales_end', sa.DateTime(), nullable=False),
    sa.Column('min_order', sa.Integer(), nullable=True),
    sa.Column('max_order', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'event_id', name='name_event_uc')
    )
    op.create_table('booked_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ticket_id', name='user_ticket_uc')
    )
    op.add_column(u'pages', sa.Column('index', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'pages', 'index')
    op.drop_table('booked_ticket')
    op.drop_table('ticket')
    ### end Alembic commands ###
