"""empty message

Revision ID: f873b99e5be3
Revises: 047f7c3db184
Create Date: 2016-07-15 22:54:20.423244

"""

# revision identifiers, used by Alembic.
revision = 'f873b99e5be3'
down_revision = '047f7c3db184'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'pages', sa.Column('index', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'pages', 'index')
    ### end Alembic commands ###
