"""empty message

Revision ID: facee76912bc
Revises: ba651e8ce9a3
Create Date: 2019-07-17 09:43:48.137732

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'facee76912bc'
down_revision = 'ba651e8ce9a3'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_invoices', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'event_invoices', 'orders', ['order_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_invoices', type_='foreignkey')
    op.drop_column('event_invoices', 'order_id')
    # ### end Alembic commands ###
