"""empty message

Revision ID: fea0fa56ded9
Revises: 4163ebc03101
Create Date: 2016-08-09 16:53:57.433514

"""

# revision identifiers, used by Alembic.
revision = 'fea0fa56ded9'
down_revision = '4163ebc03101'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_tag', sa.Column('event_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ticket_tag', 'events', ['event_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ticket_tag', type_='foreignkey')
    op.drop_column('ticket_tag', 'event_id')
    ### end Alembic commands ###
