"""empty message

Revision ID: d92b04bfc2eb
Revises: 0efe87a56e46
Create Date: 2021-02-20 18:40:40.501171

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'd92b04bfc2eb'
down_revision = '0efe87a56e46'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exhibitors', sa.Column('thumbnail_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exhibitors', 'thumbnail_image_url')
    # ### end Alembic commands ###
