"""empty message

Revision ID: 4642459983c0
Revises: 5ce97283f4bd
Create Date: 2020-11-21 21:05:50.950332

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4642459983c0'
down_revision = '5ce97283f4bd'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DELETE FROM orders_tickets WHERE deleted_at IS NOT NULL')
    op.execute('DELETE FROM orders WHERE deleted_at IS NOT NULL')
    op.drop_column('orders', 'deleted_at')
    op.drop_column('orders_tickets', 'deleted_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders_tickets', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
