"""empty message

Revision ID: e7e952b58504
Revises: 414c776ae509
Create Date: 2024-03-23 08:47:20.614874

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7e952b58504'
down_revision = '414c776ae509'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_holders', sa.Column('identifier', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_holders', 'identifier')
    # ### end Alembic commands ###
