"""empty message

Revision ID: 99361377c6b6
Revises: a3fb59fea6c2
Create Date: 2021-01-15 23:24:18.559797

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '99361377c6b6'
down_revision = 'a3fb59fea6c2'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('slug_event_topic_id', table_name='event_sub_topics')
    op.create_unique_constraint('slug_event_topic_id', 'event_sub_topics', ['slug', 'event_topic_id'])
    op.alter_column('groups', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('slug_event_topic_id', 'event_sub_topics', type_='unique')
    op.create_index('slug_event_topic_id', 'event_sub_topics', ['slug', 'event_topic_id'], unique=True)
    # ### end Alembic commands ###
