"""empty message

Revision ID: fb8dd6aed9a9
Revises: 3b29ea38f0cb
Create Date: 2021-01-08 15:32:58.996302

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'fb8dd6aed9a9'
down_revision = '3b29ea38f0cb'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('speaker', 'rank', new_column_name='order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('speaker', 'order', new_column_name='rank')
    # ### end Alembic commands ###
