"""empty message

Revision ID: 7ddfc1ae036c
Revises: 9c2b56ad8edb
Create Date: 2021-07-14 19:02:29.870427

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '7ddfc1ae036c'
down_revision = '9c2b56ad8edb'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('is_cfs_enabled', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('events_version', sa.Column('is_cfs_enabled', sa.Boolean(), server_default='False', autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events_version', 'is_cfs_enabled')
    op.drop_column('events', 'is_cfs_enabled')
    # ### end Alembic commands ###
