"""remove stripe authorization soft delete

Revision ID: 51ad369b558b
Revises: f19f66ce1467
Create Date: 2021-04-23 16:04:02.308272

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '51ad369b558b'
down_revision = 'f19f66ce1467'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('delete from stripe_authorizations where deleted_at is not null')
    op.drop_column('stripe_authorizations', 'deleted_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stripe_authorizations', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
