"""empty message

Revision ID: ec00fcbb3994
Revises: 19c591aa2ff0
Create Date: 2020-12-07 00:34:43.751344

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'ec00fcbb3994'
down_revision = '19c591aa2ff0'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('video_streams_event_id_key', 'video_streams', ['event_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('video_streams_event_id_key', 'video_streams', type_='unique')
    # ### end Alembic commands ###
