"""empty message

Revision ID: 410e54b84481
Revises: a45167cdc102
Create Date: 2023-06-12 13:39:49.999962

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '410e54b84481'
down_revision = 'a45167cdc102'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('stripe_mode', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'stripe_mode')
    # ### end Alembic commands ###
