"""empty message

Revision ID: 931f017d9b9a
Revises: a45167cdc102
Create Date: 2022-04-06 12:04:48.117924

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '931f017d9b9a'
down_revision = 'a45167cdc102'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('isScript', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'isScript')
    # ### end Alembic commands ###
