"""Add speaker.address

Revision ID: 0c584e84a77b
Revises: f90a6185c469
Create Date: 2021-01-31 01:41:31.424931

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '0c584e84a77b'
down_revision = 'f90a6185c469'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('speaker', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('speaker', 'address')
    # ### end Alembic commands ###
