"""empty message

Revision ID: 295e44c2202b
Revises: ec00fcbb3994
Create Date: 2020-12-10 05:14:25.106881

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '295e44c2202b'
down_revision = '447e39dd5fc2'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('api_url', sa.String(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('video_streams', sa.Column('channel_id', sa.Integer(), nullable=True))
    op.create_foreign_key('video_streams_channel_id_fkey', 'video_streams', 'video_channels', ['channel_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('video_streams_channel_id_fkey', 'video_streams', type_='foreignkey')
    op.drop_column('video_streams', 'channel_id')
    op.drop_table('video_channels')
    # ### end Alembic commands ###
