"""empty message

Revision ID: 29ee2c2a5841
Revises: 3dc452ffb702
Create Date: 2019-10-19 14:02:06.047516

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '29ee2c2a5841'
down_revision = '3dc452ffb702'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('organizer_email', sa.String(), nullable=False))
    op.add_column('events_version', sa.Column('organizer_email', sa.String(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events_version', 'organizer_email')
    op.drop_column('events', 'organizer_email')
    # ### end Alembic commands ###
