"""empty message

Revision ID: eb2a710fb279
Revises: f177c14710f1
Create Date: 2020-06-30 22:24:01.830211

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'eb2a710fb279'
down_revision = 'f177c14710f1'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_event_discount_code_deleted_at', 'discount_codes', ['event_id', 'code', 'deleted_at'])
    op.drop_constraint('uq_event_discount_code', 'discount_codes', type_='unique')
    op.add_column('permissions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint('role_service_deleted_at_uc', 'permissions', ['role_id', 'service_id', 'deleted_at'])
    op.drop_constraint('role_service_uc', 'permissions', type_='unique')
    op.create_unique_constraint('email_role_event_deleted_at_uc', 'role_invites', ['email', 'role_id', 'event_id', 'deleted_at'])
    op.drop_constraint('email_role_event_uc', 'role_invites', type_='unique')
    op.add_column('ticket_fees', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_fees', 'deleted_at')
    op.create_unique_constraint('email_role_event_uc', 'role_invites', ['email', 'role_id', 'event_id'])
    op.drop_constraint('email_role_event_deleted_at_uc', 'role_invites', type_='unique')
    op.create_unique_constraint('role_service_uc', 'permissions', ['role_id', 'service_id'])
    op.drop_constraint('role_service_deleted_at_uc', 'permissions', type_='unique')
    op.drop_column('permissions', 'deleted_at')
    op.create_unique_constraint('uq_event_discount_code', 'discount_codes', ['event_id', 'code'])
    op.drop_constraint('uq_event_discount_code_deleted_at', 'discount_codes', type_='unique')
    # ### end Alembic commands ###
