"""empty message

Revision ID: 44b156252c0c
Revises: 9881f067213b
Create Date: 2023-07-20 16:56:27.092506

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '44b156252c0c'
down_revision = '9881f067213b'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_check_in',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('ticket_holder_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('track_name', sa.String(), nullable=True),
    sa.Column('session_name', sa.String(), nullable=True),
    sa.Column('speaker_name', sa.String(), nullable=True),
    sa.Column('check_in_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_id'], ['station.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_holder_id'], ['ticket_holders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_check_in')
    # ### end Alembic commands ###
