"""empty message

Revision ID: 9540464e9b57
Revises: 085a8e2fdfed
Create Date: 2020-06-20 18:57:43.343701

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from app.models.custom_form import assign_field_names


# revision identifiers, used by Alembic.
revision = '9540464e9b57'
down_revision = '085a8e2fdfed'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_forms', sa.Column('name', sa.String(), nullable=True))
    assign_field_names(op)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_forms', 'name')
    # ### end Alembic commands ###
