"""empty message

Revision ID: 91b2f04ece3a
Revises: 9c089548528f
Create Date: 2021-01-09 14:24:24.828794

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '91b2f04ece3a'
down_revision = '9c089548528f'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('no_front', sa.Boolean(), nullable=False))
    op.drop_column('events', 'is_front')
    op.add_column('events_version', sa.Column('no_front', sa.Boolean(), autoincrement=False, nullable=True))
    op.drop_column('events_version', 'is_front')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events_version', sa.Column('is_front', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('events_version', 'no_front')
    op.add_column('events', sa.Column('is_front', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('events', 'no_front')
    # ### end Alembic commands ###
