"""Event identifier unique

Revision ID: f90a6185c469
Revises: 51f48128d87f
Create Date: 2021-01-28 10:02:24.889811

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'f90a6185c469'
down_revision = '51f48128d87f'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'identifier',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'events', ['identifier'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='unique')
    op.alter_column('events', 'identifier',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
