"""empty message

Revision ID: badfe92f7fea
Revises: c4100d6a5609
Create Date: 2023-07-31 18:27:31.338697

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'badfe92f7fea'
down_revision = 'c4100d6a5609'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('badge_field_forms', 'font_weight',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               postgresql_using='font_weight::json',
               existing_nullable=True),
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('badge_field_forms', 'font_weight',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
