"""empty message

Revision ID: 59e8c6ed13c4
Revises: 29ee2c2a5841
Create Date: 2019-10-19 14:27:35.134620

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '59e8c6ed13c4'
down_revision = '29ee2c2a5841'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events_version', sa.Column('organizer_email', sa.String(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events_version', 'organizer_email')
    # ### end Alembic commands ###
