"""empty message

Revision ID: 9c089548528f
Revises: fb8dd6aed9a9
Create Date: 2021-01-09 14:20:15.288961

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '9c089548528f'
down_revision = 'fb8dd6aed9a9'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('is_front', sa.Boolean(), nullable=False))
    op.add_column('events_version', sa.Column('is_front', sa.Boolean(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events_version', 'is_front')
    op.drop_column('events', 'is_front')
    # ### end Alembic commands ###
