"""empty message

Revision ID: 2fd0c27e5c95
Revises: cd0e3edd52f9
Create Date: 2020-12-20 13:57:02.234892

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '2fd0c27e5c95'
down_revision = 'cd0e3edd52f9'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('custom_forms', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False, server_default='False')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('custom_forms', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
