"""empty message

Revision ID: 576e8d0170ba
Revises: b8250aa26422
Create Date: 2020-08-27 13:26:51.581988

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '576e8d0170ba'
down_revision = 'b8250aa26422'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events_version', sa.Column('online', sa.Boolean(), server_default='False', autoincrement=False, nullable=True))
    op.drop_column('events_version', 'is_event_online')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events_version', sa.Column('is_event_online', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('events_version', 'online')
    # ### end Alembic commands ###
