"""empty message

Revision ID: 6cf73739bc9b
Revises: e3075e4e1327
Create Date: 2023-07-25 21:57:11.375459

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cf73739bc9b'
down_revision = 'e3075e4e1327'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('microlocations', sa.Column('is_chat_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('microlocations', 'is_chat_enabled')
    # ### end Alembic commands ###
