"""User add public profile and name

Revision ID: 26f3611683b9
Revises: d92b04bfc2eb
Create Date: 2021-02-23 02:48:07.670194

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '26f3611683b9'
down_revision = 'd92b04bfc2eb'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('public_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_profile_public', sa.Boolean(), server_default='True', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_profile_public')
    op.drop_column('users', 'public_name')
    # ### end Alembic commands ###
