"""empty message

Revision ID: 102aec60f690
Revises: 9afc35c9f00f
Create Date: 2021-01-21 01:28:36.928302

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '102aec60f690'
down_revision = '9afc35c9f00f'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE custom_forms SET name='Photo & video & text consent' WHERE form='attendee' and (field_identifier='acceptVideoRecording');")
    op.execute("UPDATE custom_forms SET name='Accepted to share details with sponsors' WHERE form='attendee' and(field_identifier='acceptShareDetails');")
    op.execute("UPDATE custom_forms SET name='Accepted to receive emails' WHERE form='attendee' and (field_identifier='acceptReceiveEmails');")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE custom_forms SET name='Accept Video Recording' WHERE form='attendee' and (field_identifier='acceptVideoRecording');")
    op.execute("UPDATE custom_forms SET name='Accept Share Details' WHERE form='attendee' and(field_identifier='acceptShareDetails');")
    op.execute("UPDATE custom_forms SET name='Accept Receive Emails' WHERE form='attendee' and (field_identifier='acceptReceiveEmails');")
    # ### end Alembic commands ###
