"""Add session rating count

Revision ID: 16d8d69a64e4
Revises: 64021ad8ea0e
Create Date: 2021-02-05 19:56:46.647723

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '16d8d69a64e4'
down_revision = '64021ad8ea0e'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('rating_count', sa.Integer(), server_default='0', nullable=False))
    op.execute('update sessions set rating_count = (select count(*) from feedback where session_id = sessions.id)')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'rating_count')
    # ### end Alembic commands ###
