"""empty message

Revision ID: d1c2b8711223
Revises: 9effd270a6ae
Create Date: 2019-09-15 08:29:32.373041

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'd1c2b8711223'
down_revision = '9effd270a6ae'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'is_billing_info_mandatory',
               existing_type=sa.BOOLEAN(),
               server_default='False',
               nullable=False)
    op.alter_column('orders', 'is_billing_enabled',
               existing_type=sa.BOOLEAN(),
               server_default='False',
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'is_billing_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('events', 'is_billing_info_mandatory',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
