"""empty message

Revision ID: cd0e3edd52f9
Revises: 73dad592fcd6
Create Date: 2020-12-19 13:38:15.378005

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'cd0e3edd52f9'
down_revision = '73dad592fcd6'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_forms', sa.Column('is_public', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_forms', 'is_public')
    # ### end Alembic commands ###
