"""empty message

Revision ID: 73dad592fcd6
Revises: f6bd6bce0205
Create Date: 2020-12-11 08:51:44.229142

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '73dad592fcd6'
down_revision = 'f6bd6bce0205'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_channels', sa.Column('api_key', sa.String(), nullable=True))
    op.add_column('video_streams', sa.Column('extra', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_streams', 'extra')
    op.drop_column('video_channels', 'api_key')
    # ### end Alembic commands ###
