"""empty message

Revision ID: 21c79d253f21
Revises: c4100d6a5609
Create Date: 2023-08-01 09:43:36.773097

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21c79d253f21'
down_revision = 'c4100d6a5609'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translation_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_stream_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['video_channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_stream_id'], ['video_streams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('translation_channels')
    # ### end Alembic commands ###
