"""empty message

Revision ID: ba18237b3fa9
Revises: 51ad369b558b
Create Date: 2021-06-03 08:57:08.834530

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ba18237b3fa9'
down_revision = '51ad369b558b'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_actions')
    op.alter_column('discount_codes', 'code',
               existing_type=sa.VARCHAR(),
               type_=citext.CIText(),
               existing_nullable=False)
    op.add_column('events', sa.Column('is_chat_enabled', sa.Boolean(), nullable=False))
    op.add_column('events', sa.Column('chat_room_id', sa.String(), nullable=True))
    op.add_column('events_version', sa.Column('is_chat_enabled', sa.Boolean(), autoincrement=False, nullable=True))
    op.add_column('events_version', sa.Column('chat_room_id', sa.String(), autoincrement=False, nullable=True))
    op.add_column('exhibitors', sa.Column('thumbnail_image_url', sa.String(), nullable=True))
    op.add_column('exhibitors', sa.Column('enable_video_room', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('message_settings', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('message_settings', sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('message_settings', sa.Column('enabled', sa.Boolean(), server_default='True', nullable=False))
    op.alter_column('message_settings', 'action',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('message_settings', 'mail_status')
    op.drop_column('message_settings', 'notification_status')
    op.drop_column('message_settings', 'sent_at')
    op.drop_column('message_settings', 'user_control_status')
    op.add_column('microlocations', sa.Column('hidden_in_scheduler', sa.Boolean(), nullable=False))
    op.add_column('notifications', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('notifications', sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('notifications', sa.Column('content_id', sa.Integer(), nullable=False))
    op.alter_column('notifications', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_foreign_key(None, 'notifications', 'notification_content', ['content_id'], ['id'], ondelete='CASCADE')
    op.drop_column('notifications', 'title')
    op.drop_column('notifications', 'message')
    op.drop_column('notifications', 'received_at')
    op.drop_column('notifications', 'deleted_at')
    op.add_column('sessions', sa.Column('mastodon', sa.String(), nullable=True))
    op.add_column('sessions', sa.Column('favourite_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('settings', sa.Column('rocket_chat_url', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('rocket_chat_registration_secret', sa.String(), nullable=True))
    op.add_column('speaker', sa.Column('mastodon', sa.String(), nullable=True))
    op.alter_column('speaker', 'email',
               existing_type=sa.VARCHAR(),
               type_=citext.CIText(),
               existing_nullable=True)
    op.drop_column('stripe_authorizations', 'deleted_at')
    op.alter_column('ticket_holders', 'email',
               existing_type=sa.VARCHAR(),
               type_=citext.CIText(),
               existing_nullable=True)
    op.add_column('users', sa.Column('is_profile_public', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('users', sa.Column('public_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('rocket_chat_token', sa.String(), nullable=True))
    op.alter_column('users', '_email',
               existing_type=sa.VARCHAR(length=120),
               type_=citext.CIText(),
               existing_nullable=False)
    op.add_column('video_stream_moderators', sa.Column('email', citext.CIText(), nullable=False))
    op.drop_constraint('user_video_stream_id', 'video_stream_moderators', type_='unique')
    op.create_unique_constraint('uq_user_email_video_stream_moderator', 'video_stream_moderators', ['email', 'video_stream_id'])
    op.drop_constraint('video_stream_moderators_user_id_fkey', 'video_stream_moderators', type_='foreignkey')
    op.drop_column('video_stream_moderators', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_stream_moderators', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('video_stream_moderators_user_id_fkey', 'video_stream_moderators', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_user_email_video_stream_moderator', 'video_stream_moderators', type_='unique')
    op.create_unique_constraint('user_video_stream_id', 'video_stream_moderators', ['user_id', 'video_stream_id'])
    op.drop_column('video_stream_moderators', 'email')
    op.alter_column('users', '_email',
               existing_type=citext.CIText(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.drop_column('users', 'rocket_chat_token')
    op.drop_column('users', 'public_name')
    op.drop_column('users', 'is_profile_public')
    op.alter_column('ticket_holders', 'email',
               existing_type=citext.CIText(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.add_column('stripe_authorizations', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.alter_column('speaker', 'email',
               existing_type=citext.CIText(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('speaker', 'mastodon')
    op.drop_column('settings', 'rocket_chat_registration_secret')
    op.drop_column('settings', 'rocket_chat_url')
    op.drop_column('sessions', 'favourite_count')
    op.drop_column('sessions', 'mastodon')
    op.add_column('notifications', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('received_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('notifications', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('notifications', 'content_id')
    op.drop_column('notifications', 'modified_at')
    op.drop_column('notifications', 'created_at')
    op.drop_column('microlocations', 'hidden_in_scheduler')
    op.add_column('message_settings', sa.Column('user_control_status', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('message_settings', sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('message_settings', sa.Column('notification_status', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('message_settings', sa.Column('mail_status', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('message_settings', 'action',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('message_settings', 'enabled')
    op.drop_column('message_settings', 'modified_at')
    op.drop_column('message_settings', 'created_at')
    op.drop_column('exhibitors', 'enable_video_room')
    op.drop_column('exhibitors', 'thumbnail_image_url')
    op.drop_column('events_version', 'chat_room_id')
    op.drop_column('events_version', 'is_chat_enabled')
    op.drop_column('events', 'chat_room_id')
    op.drop_column('events', 'is_chat_enabled')
    op.alter_column('discount_codes', 'code',
               existing_type=citext.CIText(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.create_table('notification_actions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('action_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('subject', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('subject_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notification_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], name='notification_actions_notification_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='notification_actions_pkey')
    )
    # ### end Alembic commands ###
