"""add rocket chat

Revision ID: 5900f4433257
Revises: 8fcb77246ccf
Create Date: 2021-03-09 10:07:46.479420

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '5900f4433257'
down_revision = '8fcb77246ccf'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('rocket_chat_registration_secret', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('rocket_chat_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'rocket_chat_url')
    op.drop_column('settings', 'rocket_chat_registration_secret')
    # ### end Alembic commands ###
