"""empty message

Revision ID: 19c591aa2ff0
Revises: 060a77f9a1ea
Create Date: 2020-12-06 06:27:36.427155

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '19c591aa2ff0'
down_revision = '060a77f9a1ea'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_streams', sa.Column('event_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'video_streams', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video_streams', type_='foreignkey')
    op.drop_column('video_streams', 'event_id')
    # ### end Alembic commands ###
