"""empty message

Revision ID: 9afc35c9f00f
Revises: 090edbf94df2
Create Date: 2021-01-18 00:12:27.574997

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '9afc35c9f00f'
down_revision = '090edbf94df2'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_holders', sa.Column('instagram', sa.String(), nullable=True))
    op.add_column('ticket_holders', sa.Column('linkedin', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_holders', 'linkedin')
    op.drop_column('ticket_holders', 'instagram')
    # ### end Alembic commands ###
