"""empty message

Revision ID: 09c177e36ac2
Revises: 528e99098827
Create Date: 2021-09-04 21:16:18.309940

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '09c177e36ac2'
down_revision = '528e99098827'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tax', 'zip',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tax', 'zip',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
