"""empty message

Revision ID: fae5670bd8c1
Revises: d228ae06060b
Create Date: 2021-01-08 14:49:46.109209

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fae5670bd8c1'
down_revision = 'd228ae06060b'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_favourite_sessions', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_favourite_sessions', sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint('uq_session_user', 'user_favourite_sessions', ['session_id', 'user_id'])
    op.drop_column('user_favourite_sessions', 'deleted_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_favourite_sessions', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint('uq_session_user', 'user_favourite_sessions', type_='unique')
    op.drop_column('user_favourite_sessions', 'modified_at')
    op.drop_column('user_favourite_sessions', 'created_at')
    # ### end Alembic commands ###
