"""empty message

Revision ID: 8e86e0ddc9a4
Revises: 3fe3442b7a13
Create Date: 2020-09-25 11:11:26.463543

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '8e86e0ddc9a4'
down_revision = '3fe3442b7a13'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('admin_billing_paypal_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'admin_billing_paypal_email')
    # ### end Alembic commands ###
