"""empty message

Revision ID: a15294581397
Revises: 8cf2327b952b
Create Date: 2023-06-22 11:53:16.566102

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a15294581397'
down_revision = '8cf2327b952b'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_holders', sa.Column('is_consent_form_field', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_holders', 'is_consent_form_field')
    # ### end Alembic commands ###
