"""empty message

Revision ID: c09e0327c6cb
Revises: ed141a4b57df
Create Date: 2021-10-09 20:25:22.399735

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'c09e0327c6cb'
down_revision = 'ed141a4b57df'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('language_prefrence', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'language_prefrence')
    # ### end Alembic commands ###
