"""empty message

Revision ID: 463da3ac8b49
Revises: a9266ead39d4
Create Date: 2021-04-14 17:53:49.462324

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '463da3ac8b49'
down_revision = 'a9266ead39d4'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_uer_user_group_role', 'users_groups_roles', type_='unique')
    op.create_unique_constraint('uq_uer_user_group_role', 'users_groups_roles', ['email', 'user_id', 'group_id', 'role_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_uer_user_group_role', 'users_groups_roles', type_='unique')
    op.create_unique_constraint('uq_uer_user_group_role', 'users_groups_roles', ['user_id', 'group_id', 'role_id'])
    # ### end Alembic commands ###
