"""empty message

Revision ID: 19168ff996c6
Revises: 3548da69bdec
Create Date: 2020-09-10 19:22:53.695773

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '19168ff996c6'
down_revision = '3548da69bdec'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_links', sa.Column('is_custom', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_links', 'is_custom')
    # ### end Alembic commands ###
