"""empty message

Revision ID: 61bec04ae010
Revises: 507022789bcb
Create Date: 2020-08-08 16:56:27.061106

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '61bec04ae010'
down_revision = '507022789bcb'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE mails set action = 'Session State Change' WHERE action = 'Session Accept or Reject'")
    op.execute("UPDATE message_settings set action = 'Session State Change' WHERE action = 'Session Accept or Reject'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE mails set action = 'Session Accept or Reject' WHERE action = 'Session State Change'")
    op.execute("UPDATE message_settings set action = 'Session Accept or Reject' WHERE action = 'Session State Change'")
    # ### end Alembic commands ###
