"""empty message

Revision ID: c7004268c3a7
Revises: 78f3c24b41cf
Create Date: 2021-08-10 19:43:54.527953

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'c7004268c3a7'
down_revision = '78f3c24b41cf'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('is_announced', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('events_version', sa.Column('is_announced', sa.Boolean(), server_default='False', autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events_version', 'is_announced')
    op.drop_column('events', 'is_announced')
    # ### end Alembic commands ###
