"""empty message

Revision ID: c6f5d0b0ae48
Revises: bf42a2f36c31
Create Date: 2021-10-29 17:10:16.886654

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'c6f5d0b0ae48'
down_revision = 'bf42a2f36c31'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('stripe_payment_intent_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'stripe_payment_intent_id')
    # ### end Alembic commands ###
