"""empty message

Revision ID: f736b1d888a7
Revises: 19168ff996c6
Create Date: 2020-09-16 01:15:24.219374

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'f736b1d888a7'
down_revision = '19168ff996c6'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('gitter_url', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('telegram_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'telegram_url')
    op.drop_column('settings', 'gitter_url')
    # ### end Alembic commands ###
