"""remove notification actions

Revision ID: 2539c7da2bad
Revises: a02007782ba2
Create Date: 2021-04-13 15:57:10.606430

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '2539c7da2bad'
down_revision = 'a02007782ba2'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_actions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_actions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('action_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('subject', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notification_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subject_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], name='notification_actions_to_notification', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='notification_actions_pkey')
    )
    # ### end Alembic commands ###
