"""empty message

Revision ID: 7a4ac439ef4d
Revises: a15294581397
Create Date: 2023-06-26 18:45:58.326001

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a4ac439ef4d'
down_revision = 'a15294581397'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_holders', sa.Column('wiki_scholarship', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_holders', 'wiki_scholarship')
    # ### end Alembic commands ###
