"""empty message

Revision ID: 6874747d4c65
Revises: 102aec60f690
Create Date: 2021-01-21 21:02:25.560034

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '6874747d4c65'
down_revision = '102aec60f690'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE custom_forms SET name='Partner contact consent' WHERE form='attendee' and(field_identifier='acceptShareDetails');")
    op.execute("UPDATE custom_forms SET name='Email consent' WHERE form='attendee' and (field_identifier='acceptReceiveEmails');")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE custom_forms SET name='Accepted to share details with sponsors' WHERE form='attendee' and(field_identifier='acceptShareDetails');")
    op.execute("UPDATE custom_forms SET name='Accepted to receive emails' WHERE form='attendee' and (field_identifier='acceptReceiveEmails');")
    # ### end Alembic commands ###
