"""empty message

Revision ID: 321c0bf9a52d
Revises: f177c14710f1
Create Date: 2020-07-03 02:08:01.440819

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '321c0bf9a52d'
down_revision = 'f177c14710f1'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_event_discount_code', 'discount_codes', type_='unique')
    op.create_unique_constraint('uq_event_discount_code', 'discount_codes', ['event_id', 'code', 'deleted_at'])
    op.drop_constraint('email_role_event_uc', 'role_invites', type_='unique')
    op.create_unique_constraint('email_role_event_uc', 'role_invites', ['email', 'role_id', 'event_id', 'deleted_at'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('email_role_event_uc', 'role_invites', type_='unique')
    op.create_unique_constraint('email_role_event_uc', 'role_invites', ['email', 'role_id', 'event_id'])
    op.drop_constraint('uq_event_discount_code', 'discount_codes', type_='unique')
    op.create_unique_constraint('uq_event_discount_code', 'discount_codes', ['event_id', 'code'])
    # ### end Alembic commands ###
