"""Add exhibitor.social_links

Revision ID: d0ac0e357cd9
Revises: 8601d512262a
Create Date: 2021-02-03 17:36:38.023250

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'd0ac0e357cd9'
down_revision = '8601d512262a'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exhibitors', sa.Column('social_links', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exhibitors', 'social_links')
    # ### end Alembic commands ###
