"""empty message

Revision ID: 5b53dc97de89
Revises: c09e0327c6cb
Create Date: 2021-10-14 07:33:18.549726

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '5b53dc97de89'
down_revision = 'c09e0327c6cb'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('is_promoted', sa.Boolean(), nullable=False, server_default='False'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'is_promoted')
    # ### end Alembic commands ###
