"""empty message

Revision ID: 2df5270f9ff3
Revises: 8b5bc48e1d4c
Create Date: 2023-08-04 10:35:07.106392

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2df5270f9ff3'
down_revision = '8b5bc48e1d4c'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_holders', sa.Column('is_discount_applied', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_holders', 'is_discount_applied')
    # ### end Alembic commands ###
