"""empty message

Revision ID: 2d3705de8180
Revises: f508644acbd3
Create Date: 2023-07-16 15:45:05.166587

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2d3705de8180'
down_revision = 'f508644acbd3'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badge_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('badge_id', sa.String(), nullable=False),
    sa.Column('badge_size', sa.String(), nullable=True),
    sa.Column('badge_color', sa.String(), nullable=True),
    sa.Column('badge_image_url', sa.String(), nullable=True),
    sa.Column('badge_orientation', sa.String(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('badge_field_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('badge_form_id', sa.Integer(), nullable=True),
    sa.Column('badge_id', sa.String(), nullable=False),
    sa.Column('field_identifier', sa.String(), nullable=True),
    sa.Column('custom_field', sa.String(), nullable=True),
    sa.Column('sample_text', sa.String(), nullable=True),
    sa.Column('font_size', sa.Integer(), nullable=True),
    sa.Column('font_name', sa.String(), nullable=True),
    sa.Column('font_weight', sa.Integer(), nullable=True),
    sa.Column('font_color', sa.String(), nullable=True),
    sa.Column('text_rotation', sa.Integer(), nullable=True),
    sa.Column('text_alignment', sa.String(), nullable=True),
    sa.Column('text_type', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('margin_top', sa.Integer(), nullable=True),
    sa.Column('margin_bottom', sa.Integer(), nullable=True),
    sa.Column('margin_left', sa.Integer(), nullable=True),
    sa.Column('margin_right', sa.Integer(), nullable=True),
    sa.Column('qr_custom_field', postgresql.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['badge_form_id'], ['badge_forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('events', sa.Column('is_badges_enabled', sa.Boolean(), nullable=True))
    op.add_column('events_version', sa.Column('is_badges_enabled', sa.Boolean(), autoincrement=False, nullable=True))
    op.add_column('tickets', sa.Column('badge_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'badge_id')
    op.drop_column('events_version', 'is_badges_enabled')
    op.drop_column('events', 'is_badges_enabled')
    op.drop_table('badge_field_forms')
    op.drop_table('badge_forms')
    # ### end Alembic commands ###
