"""Add speaker timestamps

Revision ID: b75a8dd29262
Revises: fbca765f3c76
Create Date: 2021-02-02 10:56:23.928404

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'b75a8dd29262'
down_revision = 'fbca765f3c76'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('speaker', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('speaker', sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('speaker', 'modified_at')
    op.drop_column('speaker', 'created_at')
    # ### end Alembic commands ###
