"""empty message

Revision ID: 447e39dd5fc2
Revises: ec00fcbb3994
Create Date: 2020-12-10 13:19:11.810552

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '447e39dd5fc2'
down_revision = 'ec00fcbb3994'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('admin_billing_logo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'admin_billing_logo')
    # ### end Alembic commands ###
