"""empty message

Revision ID: a8d58b96b916
Revises: 605687849d3c
Create Date: 2021-07-08 17:33:10.673056

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'a8d58b96b916'
down_revision = '605687849d3c'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('about', sa.Text(), nullable=True))
    op.add_column('groups', sa.Column('banner_url', sa.String(), nullable=True))
    op.add_column('groups', sa.Column('logo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'logo_url')
    op.drop_column('groups', 'banner_url')
    op.drop_column('groups', 'about')
    # ### end Alembic commands ###
