"""empty message

Revision ID: 99217a8bc9b2
Revises: 08e4b2df44a3
Create Date: 2020-09-30 13:00:05.338258

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99217a8bc9b2'
down_revision = '08e4b2df44a3'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_invoices', sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_invoices', 'issued_at')
    # ### end Alembic commands ###
