"""empty message

Revision ID: ab0e4baaabab
Revises: f52267133dcc
Create Date: 2021-07-22 00:49:24.222025

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'ab0e4baaabab'
down_revision = 'f52267133dcc'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('slides', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'slides')
    # ### end Alembic commands ###
