"""empty message

Revision ID: b0985248e3d9
Revises: c4fc87788cd5
Create Date: 2021-12-09 16:49:44.905527

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'b0985248e3d9'
down_revision = 'c4fc87788cd5'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('stripe_payment_intent_id', sa.String(), nullable=True))
    op.drop_column('orders', 'stripe_session_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('stripe_session_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('orders', 'stripe_payment_intent_id')
    # ### end Alembic commands ###
