"""empty message

Revision ID: 6af91cb7532a
Revises: a9266ead39d4
Create Date: 2021-04-14 21:55:07.047634

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '6af91cb7532a'
down_revision = 'a9266ead39d4'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_uer_user_group_role', 'users_groups_roles', type_='unique')
    op.create_unique_constraint('uq_uer_user_group_role_1', 'users_groups_roles', ['user_id', 'group_id', 'role_id'])
    op.create_unique_constraint('uq_uer_user_group_role_2', 'users_groups_roles', ['email', 'group_id', 'role_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_uer_user_group_role_2', 'users_groups_roles', type_='unique')
    op.drop_constraint('uq_uer_user_group_role_1', 'users_groups_roles', type_='unique')
    op.create_unique_constraint('uq_uer_user_group_role', 'users_groups_roles', ['user_id', 'group_id', 'role_id'])
    # ### end Alembic commands ###
