"""empty message

Revision ID: 5bd31dacdd57
Revises: 9881f067213b
Create Date: 2023-07-19 16:40:02.078321

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bd31dacdd57'
down_revision = '9881f067213b'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_check_in',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('ticket_holder_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('is_check_in', sa.Boolean(), nullable=True),
    sa.Column('check_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_id'], ['station.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_holder_id'], ['ticket_holders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_check_in')
    # ### end Alembic commands ###
