"""empty message

Revision ID: a739ff6a3855
Revises: 51ad369b558b
Create Date: 2021-04-23 22:23:47.165020

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'a739ff6a3855'
down_revision = 'f19f66ce1476'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_recordings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bbb_record_id', sa.String(), nullable=True),
    sa.Column('participants', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('video_stream_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['video_stream_id'], ['video_streams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_recordings')
    # ### end Alembic commands ###
