"""empty message

Revision ID: b8250aa26422
Revises: be959d7b84d4
Create Date: 2020-08-27 13:19:10.560356

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'b8250aa26422'
down_revision = 'be959d7b84d4'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE events SET is_event_online = false where is_event_online is null")
    op.alter_column('events', 'is_event_online',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default='False')
    op.alter_column('events', 'is_event_online', new_column_name='online')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'online', new_column_name='is_event_online')
    op.alter_column('events', 'is_event_online',
               existing_type=sa.BOOLEAN(),
               nullable=True)
