"""empty message

Revision ID: 74a148c0100d
Revises: aa9daed401f7
Create Date: 2020-11-16 15:19:38.949153

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '74a148c0100d'
down_revision = 'aa9daed401f7'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('weblate_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'weblate_url')
    # ### end Alembic commands ###
