"""empty message

Revision ID: f940bc05ba93
Revises: 528e99098827
Create Date: 2021-08-26 18:46:53.110836

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'f940bc05ba93'
down_revision = '528e99098827'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('stripe_session_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'stripe_session_id')
    # ### end Alembic commands ###
