"""empty message

Revision ID: cbe8314bce5e
Revises: 26f3611683b9
Create Date: 2021-02-28 20:37:56.792109

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'cbe8314bce5e'
down_revision = '26f3611683b9'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('favourite_count', sa.Integer(), server_default='0', nullable=False))
    op.execute('update sessions set favourite_count = (select count(*) from user_favourite_sessions where session_id = sessions.id)')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'favourite_count')
    # ### end Alembic commands ###
