"""empty message

Revision ID: 05b1aab46b66
Revises: 7a4ac439ef4d
Create Date: 2023-06-28 15:31:13.401097

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '05b1aab46b66'
down_revision = '7a4ac439ef4d'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_holders', sa.Column('is_consent_form_field_photo', sa.Boolean(), nullable=True))
    op.add_column('ticket_holders', sa.Column('is_consent_form_field_email', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_holders', 'is_consent_form_field_email')
    op.drop_column('ticket_holders', 'is_consent_form_field_photo')
    # ### end Alembic commands ###
