"""empty message

Revision ID: 9756adf77900
Revises: b2ba7a0ea5c1
Create Date: 2021-02-11 22:30:21.041456

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '9756adf77900'
down_revision = 'b2ba7a0ea5c1'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exhibitors', sa.Column('contact', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exhibitors', 'contact')
    # ### end Alembic commands ###
