"""empty message

Revision ID: 1af4cc4f7cd5
Revises: 7e91153d66b0
Create Date: 2023-08-10 15:26:07.373388

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1af4cc4f7cd5'
down_revision = '7e91153d66b0'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ticket_holders', sa.Column('tag_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ticket_holders', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ticket_holders', type_='foreignkey')
    op.drop_column('ticket_holders', 'tag_id')
    op.drop_table('tags')
    # ### end Alembic commands ###
