"""empty message

Revision ID: edd5cb637adc
Revises: 102aec60f690
Create Date: 2021-01-24 07:16:50.475344

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'edd5cb637adc'
down_revision = '6874747d4c65'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('delete from users_events_roles where event_id is null or role_id is null or user_id is null')
    op.alter_column('users_events_roles', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users_events_roles', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users_events_roles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_events_roles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users_events_roles', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users_events_roles', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
