"""empty message

Revision ID: 3b784f9c98c7
Revises: 9881f067213b
Create Date: 2023-07-19 10:01:32.456857

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3b784f9c98c7'
down_revision = '2b19596af9f0'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_forms', sa.Column('is_allow_edit', sa.Boolean(), server_default='False', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_forms', 'is_allow_edit')
