"""empty message

Revision ID: b3cf88a46150
Revises: bf42a2f36c31
Create Date: 2021-11-06 20:56:17.061859

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'b3cf88a46150'
down_revision = 'bf42a2f36c31'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('speaker', sa.Column('speaker_positions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('speaker', 'speaker_positions')
    # ### end Alembic commands ###
