"""empty message

Revision ID: 090edbf94df2
Revises: 6314551fe3a7
Create Date: 2021-01-16 00:39:16.209666

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '090edbf94df2'
down_revision = 'eb4a6c91874d'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('after_order_message', sa.Text(), nullable=True))
    op.add_column('events_version', sa.Column('after_order_message', sa.Text(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events_version', 'after_order_message')
    op.drop_column('events', 'after_order_message')
    # ### end Alembic commands ###
