"""Remove secret from settings

Revision ID: 30a490ad1609
Revises: eef7c9bc83a12
Create Date: 2020-01-17 01:09:54.175788

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '30a490ad1609'
down_revision = 'eef7c9bc83a12'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'secret')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('secret', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
