"""empty message

Revision ID: cd8488c19b16
Revises: fb8dd6aed9a9
Create Date: 2021-01-09 18:31:24.557692

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'cd8488c19b16'
down_revision = 'fb8dd6aed9a9'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('is_demoted', sa.Boolean(), nullable=False, server_default='False'))
    op.add_column('events_version', sa.Column('is_demoted', sa.Boolean(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events_version', 'is_demoted')
    op.drop_column('events', 'is_demoted')
    # ### end Alembic commands ###
