"""empty message

Revision ID: 2d04286c9445
Revises: a742abacc9b6
Create Date: 2021-01-15 15:40:29.900233

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '2d04286c9445'
down_revision = 'a742abacc9b6'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('is_cfs_enabled', sa.Boolean(), nullable=True))
    op.add_column('events_version', sa.Column('is_cfs_enabled', sa.Boolean(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events_version', 'is_cfs_enabled')
    op.drop_column('events', 'is_cfs_enabled')
    # ### end Alembic commands ###
