"""empty message

Revision ID: 9b6873db28df
Revises: e5c599d64ef5
Create Date: 2023-06-21 10:48:11.844162

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b6873db28df'
down_revision = 'e5c599d64ef5'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_holders', sa.Column('language_form_1', sa.JSON(), nullable=True))
    op.add_column('ticket_holders', sa.Column('language_form_2', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_holders', 'language_form_2')
    op.drop_column('ticket_holders', 'language_form_1')
    # ### end Alembic commands ###
