"""empty message

Revision ID: e5c599d64ef5
Revises: d3c32d203ef1
Create Date: 2023-06-20 17:34:57.383544

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5c599d64ef5'
down_revision = 'd3c32d203ef1'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_holders', sa.Column('home_wiki', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_holders', 'home_wiki')
    # ### end Alembic commands ###
