"""empty message

Revision ID: 8b5bc48e1d4c
Revises: 21c79d253f21
Create Date: 2023-08-01 14:10:12.187180

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8b5bc48e1d4c'
down_revision = '21c79d253f21'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('badge_field_forms', 'font_weight')
    op.add_column('badge_field_forms', sa.Column('font_weight',
                                                 postgresql.ARRAY(sa.JSON()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('badge_field_forms', 'font_weight')
    op.add_column('badge_field_forms', sa.Column('font_weight',
                                                 sa.Integer(), nullable=True))
    # ### end Alembic commands ###
