"""empty message

Revision ID: a9266ead39d4
Revises: 28de2911c790
Create Date: 2021-04-13 01:29:56.441235

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import citext


# revision identifiers, used by Alembic.
revision = 'a9266ead39d4'
down_revision = 'a370f2a07c8d'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users_groups_roles',
        sa.Column('accepted', sa.Boolean(), nullable=False, server_default='False'),
    )
    op.add_column(
        'users_groups_roles', sa.Column('email', citext.CIText(), nullable=False)
    )
    op.add_column('users_groups_roles', sa.Column('token', sa.String(), nullable=True))
    op.alter_column(
        'users_groups_roles', 'user_id', existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users_groups_roles', 'user_id', existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_column('users_groups_roles', 'token')
    op.drop_column('users_groups_roles', 'email')
    op.drop_column('users_groups_roles', 'accepted')
    # ### end Alembic commands ###
