# Generated by Django 5.0 on 2023-12-23 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2147483647)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('social_links', models.JSONField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('banner_url', models.CharField(blank=True, max_length=2147483647, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=2147483647, null=True)),
                ('follower_count', models.IntegerField(default=0)),
                ('thumbnail_image_url', models.CharField(blank=True, max_length=2147483647, null=True)),
                ('is_promoted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
