# Generated by Django 5.0 on 2023-12-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='follower_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='is_promoted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='thumbnail_image_url',
            field=models.URLField(null=True),
        ),
    ]
