# Generated by Django 5.0 on 2023-12-23 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2147483647)),
                ('subtitle', models.CharField(blank=True, max_length=2147483647, null=True)),
                ('short_abstract', models.TextField(blank=True, null=True)),
                ('long_abstract', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=2147483647, null=True)),
                ('slides_url', models.CharField(blank=True, max_length=2147483647, null=True)),
                ('video_url', models.CharField(blank=True, max_length=2147483647, null=True)),
                ('audio_url', models.CharField(blank=True, max_length=2147483647, null=True)),
                ('signup_url', models.CharField(blank=True, max_length=2147483647, null=True)),
                ('state', models.CharField(blank=True, db_index=True, max_length=2147483647, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('submission_modifier', models.CharField(blank=True, max_length=2147483647, null=True)),
                ('is_mail_sent', models.BooleanField(blank=True, null=True)),
                ('level', models.CharField(blank=True, max_length=2147483647, null=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
                ('send_email', models.BooleanField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('complex_field_values', models.JSONField(blank=True, null=True)),
                ('average_rating', models.FloatField(default=0)),
                ('rating_count', models.IntegerField(default=0)),
                ('facebook', models.CharField(blank=True, max_length=2147483647, null=True)),
                ('github', models.CharField(blank=True, max_length=2147483647, null=True)),
                ('gitlab', models.CharField(blank=True, max_length=2147483647, null=True)),
                ('instagram', models.CharField(blank=True, max_length=2147483647, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=2147483647, null=True)),
                ('twitter', models.CharField(blank=True, max_length=2147483647, null=True)),
                ('website', models.CharField(blank=True, max_length=2147483647, null=True)),
                ('favourite_count', models.IntegerField(default=0)),
                ('mastodon', models.CharField(blank=True, max_length=2147483647, null=True)),
                ('slides', models.JSONField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
