# Generated by Django 5.0 on 2023-12-23 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_sessions', '0002_initial'),
        ('microlocation', '0001_initial'),
        ('session_types', '0001_initial'),
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsession',
            name='microlocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='microlocation.microlocation'),
        ),
        migrations.AddField(
            model_name='customsession',
            name='session_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='session_types.sessiontype'),
        ),
        migrations.AddField(
            model_name='customsession',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracks.track'),
        ),
    ]
