# Generated by Django 5.0 on 2023-12-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2147483647)),
                ('value', models.FloatField()),
                ('type', models.CharField(max_length=2147483647)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('tickets_number', models.IntegerField(blank=True, null=True)),
                ('min_quantity', models.IntegerField(blank=True, null=True)),
                ('max_quantity', models.IntegerField(blank=True, null=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_till', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('used_for', models.CharField(max_length=2147483647)),
                ('discount_url', models.CharField(blank=True, max_length=2147483647, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
