# Generated by Django 5.0 on 2024-03-12 03:59

import django.contrib.postgres.fields.citext
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', django.contrib.postgres.fields.citext.CICharField(max_length=255, null=True, unique=True)),
                ('value', models.FloatField()),
                ('type', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('tickets_number', models.IntegerField(blank=True, null=True)),
                ('min_quantity', models.IntegerField(blank=True, null=True)),
                ('max_quantity', models.IntegerField(blank=True, null=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_till', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('used_for', models.CharField(max_length=255)),
                ('discount_url', models.URLField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
