# Group Badge Forms
Badge Forms related to the events.

| Parameter | Description | Type | Required |
|:----------|-------------|------|----------|
| `badge-color`  | Badge Color | string | - |
| `badge-size` | Badge Size | string | - |
| `badge-id` | Badge Id | string | **yes** |
| `badge-image-url` | Badge Image Url | String | - |
| `badge-orientation` | Badge Orientation | String | - |

## Get Badge Form By Ticket [/v1/tickets/{ticket_id}/badge-forms]
+ Parameters
  + ticket_id: 1 (integer) - ID of the ticket in the form of an integer

### Get Badge Form By Ticket [GET]
Get badge form.

+ Request (application/vnd.api+json)

    + Headers

            Authorization: JWT <Auth Key>

+ Response 200 (application/json)

    [
      {
        "custom_field": "example",
        "field_identifier": "example",
        "id": 1
      }
    ]

## Print Badge [/v1/badge-forms/print-badge-pdf]

### Print Badge [POST]
Printing badge for attendee.

+ Request (application/json)

    + Headers

            Authorization: JWT <Auth Key>

    + Body

            {
                "attendee_id": 1,
                "list_field_show": ["email"]
            }

+ Response 200 (application/json)

    + Headers

            Content-Disposition: attachment; filename=7bc47998-2227-471e-83e3-8dfe211ce798.pdf

            Content-Length: 1554

            Content-Type: application/pdf

            Last-Modified: Wed, 09 Aug 2023 03:09:59 GMT

            Cache-Control: public, max-age=43200

            Expires: Wed, 09 Aug 2023 15:09:59 GMT

            Server: Werkzeug/2.0.3 Python/3.8.10
