# Group Badge Forms
Badge Forms related to the events.

| Parameter | Description | Type | Required |
|:----------|-------------|------|----------|
| `badge-color`  | Badge Color | string | - |
| `badge-size` | Badge Size | string | - |
| `badge-id` | Badge Id | string | **yes** |
| `badge-image-url` | Badge Image Url | String | - |
| `badge-orientation` | Badge Orientation | String | - |
