# Group Celery Tasks

This API helps you to get the status of a celery task and the response

## Task Details [/v1/tasks/{task_id}]
+ Parameters
    + task_id: 1 (string) - id of the task. (b7ca7088-876e-4c29-a0ee-b8029a64849a is an example of identifier)
Get the task status and the final result of the task as response


### Get Task Result [GET]

+ Request

    + Headers

            Content-Type: application/json
            Authorization: JWT <Auth Key>

+ Response 200 (application/json)

        {
            "result": {
                "download_url": "/v1/events/1/exports/http://localhost/static/media/exports/1/zip/OGpMM0w2RH/event1.zip"
            },
            "state": "SUCCESS"
        }
