# Group Exhibitors
Data related to the various exhibitors with their name, url and images associated with a specific event.

| Parameter | Description | Type | Required |
|:----------|-------------|------|----------|
| `name`  | Name of the Exhibitor | string | **yes** |
| `description` | Description | string | - |
| `url` | URL | string | - |
| `position` | Sorting position of Exhibitor | integer | - |
| `logo_url` | Logo URL | string | - |
| `banner_url` | Banner URL | string | - |
| `video_url` | Video URL | string | - |
| `slides_url` | Slides URL | string | - |
| `contact-email` | Contact Email of the Exhibitor | string | - |
| `contact-link` | Contact Link of the Exhibitor | string | - |

## Exhibitors Post Collection [/v1/exhibitors]

### Create Exhibitor [POST]
Create a new exhibitor using an event_id.

+ Request (application/vnd.api+json)

    + Headers

            Authorization: JWT <Auth Key>

    + Body

            {
              "data": {
                "relationships":{
                  "event":{
                    "data":{
                      "type":"event",
                      "id":"1"
                    }
                  }
                },
                "attributes": {
                  "name": "Fossasia",
                  "description": "Fossasia",
                  "url": "http://example.com",
                  "logo-url": "http://example.com/logo.png",
                  "video-url": "http://example.com/video.mp4",
                  "slides-url": "http://example.com/slides.pdf",
                  "contact-email": "fossasia@fossasia.org",
                  "contact-link": "http://example.com",
                  "position": 1
                },
                "type": "exhibitor"
              }
            }


+ Response 201 (application/vnd.api+json)

        {
          "data": {
            "relationships": {
              "event": {
                "links": {
                  "self": "/v1/exhibitors/1/relationships/event",
                  "related": "/v1/exhibitors/1/event"
                }
              }
            },
            "attributes": {
              "name": "Fossasia",
              "description": "Fossasia",
              "url": "http://example.com",
              "logo-url": "http://example.com/logo.png",
              "banner-url": null,
              "video-url": "http://example.com/video.mp4",
              "slides-url": "http://example.com/slides.pdf",
              "contact-email": "fossasia@fossasia.org",
              "contact-link": "http://example.com",
              "position": 1
            },
            "type": "exhibitor",
            "id": "1",
            "links": {
              "self": "/v1/exhibitors/1"
            }
          },
          "jsonapi": {
            "version": "1.0"
          },
          "links": {
            "self": "/v1/exhibitors/1"
          }
        }

## Exhibitors Get Collection [/v1/events/{event_identifier}/exhibitors{?page%5bsize%5d,page%5bnumber%5d,sort,filter}]
+ Parameters
    + event_identifier: 1 (string) - identifier or event id of the event. (b8324ae2 is an example of identifier)
    + page%5bsize%5d (optional, integer, `10`) - Maximum number of resources in a single paginated response.
    + page%5bnumber%5d (optional, integer, `2`) - Page number to fetched for the paginated response.
    + sort (optional, string, `position`) - Sort the resources according to the given attribute in ascending order. Append '-' to sort in descending order.
    + filter (optional, string, `[]`) - Filter according to the flask-rest-jsonapi filtering system. Please refer: http://flask-rest-jsonapi.readthedocs.io/en/latest/filtering.html for more.

### List All Exhibitors [GET]
Get a list of Exhibitors.

+ Request

    + Headers

            Accept: application/vnd.api+json

            Authorization: JWT <Auth Key>

+ Response 200 (application/vnd.api+json)

        {
          "meta": {
            "count": 1
          },
          "data": [
            {
              "relationships": {
                "event": {
                  "links": {
                    "self": "/v1/exhibitors/1/relationships/event",
                    "related": "/v1/exhibitors/1/event"
                  }
                }
              },
              "attributes": {
                "description": "Fossasia",
                "position": 0,
                "url": "http://example.com",
                "logo-url": "http://example.com/logo.png",
                "banner-url": "http://example.com/banner.png",
                "video-url": "http://example.com/video.mp4",
                "slides-url": "http://example.com/slides.pdf",
                "contact-email": "fossasia@fossasia.org",
                "contact-link": "http://example.com",
                "name": "Fossasia"
              },
              "type": "exhibitor",
              "id": "1",
              "links": {
                "self": "/v1/exhibitors/1"
              }
            }
          ],
          "jsonapi": {
            "version": "1.0"
          },
          "links": {
            "self": "/v1/events/1/exhibitors"
          }
        }


## Exhibitor Details [/v1/exhibitors/{exhibitor_id}]
+ Parameters
    + exhibitor_id: 1 (integer) - ID of the exhibitor in the form of an integer

### Exhibitor Details [GET]
Get a single exhibitor.

+ Request

    + Headers

            Accept: application/vnd.api+json

            Authorization: JWT <Auth Key>

+ Response 200 (application/vnd.api+json)

        {
          "data": {
            "relationships": {
              "event": {
                "links": {
                  "self": "/v1/exhibitors/1/relationships/event",
                  "related": "/v1/exhibitors/1/event"
                }
              }
            },
            "attributes": {
              "description": "Fossasia",
              "position": 0,
              "url": "http://example.com",
              "logo-url": "http://example.com/logo.png",
              "banner-url": "http://example.com/banner.png",
              "video-url": "http://example.com/video.mp4",
              "slides-url": "http://example.com/slides.pdf",
              "contact-email": "fossasia@fossasia.org",
              "contact-link": "http://example.com",
              "name": "Fossasia"
            },
            "type": "exhibitor",
            "id": "1",
            "links": {
              "self": "/v1/exhibitors/1"
            }
          },
          "jsonapi": {
            "version": "1.0"
          },
          "links": {
            "self": "/v1/exhibitors/1"
          }
        }


### Update Exhibitor [PATCH]
Update a single exhibitor by `id`.

+ `id` (integer) - ID of the record to update **(required)**

+ Request (application/vnd.api+json)

    + Headers

            Authorization: JWT <Auth Key>

    + Body

            {
              "data": {
                "attributes": {
                  "description": "Example Description",
                  "url": "http://example1.com",
                  "position": 2,
                  "name": "New Open Event Exhibitor",
                  "logo-url": "http://example.com/example1.png",
                  "video-url": "http://example.com/video1.mp4",
                  "slides-url": "http://example.com/slides1.pdf",
                  "contact-email": "fossasia@fossasia.org",
                  "contact-link": "http://example.com"
                },
                "type": "exhibitor",
                "id": "1"
              }
            }

+ Response 200 (application/vnd.api+json)

        {
          "data": {
            "relationships": {
              "event": {
                "links": {
                  "self": "/v1/exhibitors/1/relationships/event",
                  "related": "/v1/exhibitors/1/event"
                }
              }
            },
            "attributes": {
              "name": "New Open Event Exhibitor",
              "description": "Example Description",
              "url": "http://example1.com",
              "position": 2,
              "name": "New Open Event Exhibitor",
              "logo-url": "http://example.com/example1.png",
              "banner-url": null,
              "video-url": "http://example.com/video1.mp4",
              "contact-email": "fossasia@fossasia.org",
              "contact-link": "http://example.com",
              "slides-url": "http://example.com/slides1.pdf"
            },
            "type": "exhibitor",
            "id": "1",
            "links": {
              "self": "/v1/exhibitors/1"
            }
          },
          "jsonapi": {
            "version": "1.0"
          },
          "links": {
            "self": "/v1/exhibitors/1"
          }
        }

### Delete Exhibitor [DELETE]
Delete a single exhibitor.

+ Request

    + Headers

            Accept: application/vnd.api+json

            Authorization: JWT <Auth Key>

+ Response 200 (application/vnd.api+json)

        {
          "meta": {
            "message": "Object successfully deleted"
          },
          "jsonapi": {
            "version": "1.0"
          }
        }
