# Group Message Settings

**ADMIN**

To get or modify data of this data layer, you will need admin access. You can get the data without admin access as well.

| Parameter | Description | Type | Required |
|:----------|-------------|------|----------|
| `action`  | Action of the message | string | - |
| `enabled`  | Whether this Mail is enabled | boolean | - |
| `email-message`  | Message of the Email | string | - |
| `notification-message`  | Message of the Notification | string | - |

## Message Setting Collection [/v1/message-settings{?page%5bsize%5d,page%5bnumber%5d,filter}]
+ Parameters
    + page%5bsize%5d (optional, integer, `10`) - Maximum number of resources in a single paginated response.
    + page%5bnumber%5d (optional, integer, `2`) - Page number to fetched for the paginated response..
    + filter (optional, string, `[]`) - Filter according to the flask-rest-jsonapi filtering system. Please refer: http://flask-rest-jsonapi.readthedocs.io/en/latest/filtering.html for more.

### List Message Settings [GET]
Get a list of Message Settings.

+ Request

    + Headers

            Accept: application/vnd.api+json

            Authorization: JWT <Auth Key>

+ Response 200 (application/vnd.api+json)

        {
            "meta": {
                "count": 1
            },
            "data": [
                {
                    "attributes": {
                        "enabled": true,
                        "action": "event_role",
                        "recipient": "User",
                        "email-subject": "Invitation to be {role} at {event}",
                        "email-message": "Hello {email},<br><br>You have been invited to be a <strong>{role}</strong> at <strong>{event}</strong>.<br>To accept the role please sign up using the following link:{ Link }"
                    },
                    "type": "message-settings",
                    "id": "1",
                    "links": {
                        "self": "/v1/message-settings/1"
                    }
                }
            ],
            "jsonapi": {
                "version": "1.0"
            },
            "links": {
                "self": "/v1/message-settings"
            }
        }


## Message Setting Details [/v1/message-settings/{message_settings_id}]
+ Parameters
    + message_settings_id: 1 (integer) - ID of the message setting in the form of an integer

### Get Message Setting Details [GET]
Get a single message setting.

+ Request

    + Headers

            Accept: application/vnd.api+json

            Authorization: JWT <Auth Key>

+ Response 200 (application/vnd.api+json)

        {
          "data": {
            "attributes": {
                "enabled": true,
                "action": "event_role",
                "recipient": "User",
                "email-subject": "Invitation to be {role} at {event}",
                "email-message": "Hello {email},<br><br>You have been invited to be a <strong>{role}</strong> at <strong>{event}</strong>.<br>To accept the role please sign up using the following link:{ Link }"
            },
            "type": "message-setting",
            "id": "1",
            "links": {
              "self": "/v1/message-settings/1"
            }
          },
          "jsonapi": {
            "version": "1.0"
          },
          "links": {
            "self": "/v1/message-settings/1"
          }
        }


### Update Message Setting [PATCH]
Update a single message setting by `id` (only admin).

+ `id` (integer) - ID of the record to update **(required)**

+ Request (application/vnd.api+json)

    + Headers

            Authorization: JWT <Auth Key>

    + Body

            {
              "data": {
                "attributes": {
                  "enabled": true,
                  "action": "event_role"
            },
                "id": "1",
                "type": "message-setting"
              }
            }

+ Response 200 (application/vnd.api+json)

            {
                "data": {
                    "attributes": {
                        "enabled": true,
                        "action": "event_role",
                        "recipient": "User",
                        "email-subject": "Invitation to be {role} at {event}",
                        "email-message": "Hello {email},<br><br>You have been invited to be a <strong>{role}</strong> at <strong>{event}</strong>.<br>To accept the role please sign up using the following link:{ Link }"
                    },
                    "type": "message-setting",
                    "id": "1",
                    "links": {
                        "self": "/v1/message-settings/1"
                    }
                },
                "jsonapi": {
                    "version": "1.0"
                },
                "links": {
                    "self": "/v1/message-settings/1"
                }
            }
