# Group Station Store Paxs

## Create Station Store Paxs [/v1/station-store-paxs]

### Create Station Store Paxs [POST]
Create station store paxs.

+ Request (application/vnd.api+json)

    + Headers

            Authorization: JWT <Auth Key>

    + Body

            {
              "data": {
                "type": "station-store-pax",
                "relationships": {
                      "station": {
                        "data": {
                          "type": "station",
                          "id": "1"
                        }
                      },
                      "session": {
                        "data": {
                          "type": "session",
                          "id": "1"
                        }
                      }
                    },
                "attributes": {
                      "current_pax": "10"
                    }
                }
            }

+ Response 201 (application/vnd.api+json)

        {
          "data": {
              "type": "station-store-pax",
              "relationships": {
                  "session": {
                      "links": {
                          "self": "/v1/station-store-paxs/1/relationships/session",
                          "related": "/v1/sessions/1"
                      }
                  },
                  "station": {
                      "links": {
                          "self": "/v1/station-store-paxs/1/relationships/station",
                          "related": "/v1/stations/1"
                      }
                  }
              },
              "attributes": {
                  "current-pax": 10,
                  "modified-at": "2023-07-28T04:30:48.251435+00:00",
                  "created-at": "2023-07-28T04:30:48.251430+00:00"
              },
              "id": 1,
              "links": {
                  "self": "/v1/station-store-paxs/1"
              }
          },
          "links": {
              "self": "/v1/station-store-paxs/1"
          },
          "jsonapi": {
              "version": "1.0"
          }
        }

## Get Station Store Paxs By Station and Session [/v1/stations/{station_id}/sessions/{session_id}/station-store-paxs]
+ Parameters
    + station_id: 1 (integer) - ID of the station in the form of an integer
    + session_id: 1 (integer) - ID of the session in the form of an integer

### Get Station Store Paxs By Station and Session [GET]
Get station store paxs By station and session.

+ Request (application/vnd.api+json)

    + Headers

            Authorization: JWT <Auth Key>

+ Response (application/vnd.api+json)

        {"data": [], "links": {"self": "/v1/stations/1/sessions/1/station-store-paxs"}, "meta": {"count": 0}, "jsonapi": {"version": "1.0"}}
