# Group Notifications
Notifications related to the various users about invites, ticket purchase, session proposal etc.

| Parameter | Description | Type | Required |
|:----------|-------------|------|----------|
| `is-read` | Yes/No for read notification | boolean (default: `false`) | - |
| `created-at` | Notification created time | ISO 8601 (tz-aware) | - |

## Notifications Collection [/v1/users/{user_id}/notifications{?page%5bsize%5d,page%5bnumber%5d,sort,filter}]
+ Parameters
    + user_id: 2 (integer) - ID of the specific user in integer
    + page%5bsize%5d (optional, integer, `10`) - Maximum number of resources in a single paginated response.
    + page%5bnumber%5d (optional, integer, `2`) - Page number to fetched for the paginated response.
    + sort (optional, string, `created-at`) - Sort the resources according to the given attribute in ascending order. Append '-' to sort in descending order.
    + filter (optional, string, `[]`) - Filter according to the flask-rest-jsonapi filtering system. Please refer: http://flask-rest-jsonapi.readthedocs.io/en/latest/filtering.html for more.

### List All Notifications [GET]
Get a list of Notifications.

+ Request

    + Headers

            Accept: application/vnd.api+json

            Authorization: JWT <Auth Key>

+ Response 200 (application/vnd.api+json)

        {
            "meta": {
                "count": 1
            },
            "data": [
                {
                    "relationships": {
                        "user": {
                            "links": {
                                "self": "/v1/notifications/1/relationships/user",
                                "related": "/v1/notifications/1/user"
                            }
                        }
                    },
                    "attributes": {
                        "created-at": "2017-06-23T04:40:37.239724+00:00",
                        "is-read": false
                    },
                    "type": "notification",
                    "id": "1",
                    "links": {
                        "self": "/v1/notifications/1"
                    }
                }
            ],
            "jsonapi": {
                "version": "1.0"
            },
            "links": {
                "self": "/v1/users/2/notifications"
            }
        }


## Notifications Admin Collection [/v1/notifications{?page%5bsize%5d,page%5bnumber%5d,sort,filter}]
+ Parameters
    + page%5bsize%5d (optional, integer, `10`) - Maximum number of resources in a single paginated response.
    + page%5bnumber%5d (optional, integer, `2`) - Page number to fetched for the paginated response.
    + sort (optional, string, `created-at`) - Sort the resources according to the given attribute in ascending order. Append '-' to sort in descending order.
    + filter (optional, string, `[]`) - Filter according to the flask-rest-jsonapi filtering system. Please refer: http://flask-rest-jsonapi.readthedocs.io/en/latest/filtering.html for more.

### List All Notifications [GET]
Get a list of Notifications.

+ Request

    + Headers

            Accept: application/vnd.api+json

            Authorization: JWT <Auth Key>

+ Response 200 (application/vnd.api+json)

        {
            "meta": {
                "count": 1
            },
            "data": [
                {
                    "relationships": {
                        "user": {
                            "links": {
                                "self": "/v1/notifications/1/relationships/user",
                                "related": "/v1/notifications/1/user"
                            }
                        }
                    },
                    "attributes": {
                        "created-at": "2017-06-23T04:40:37.239724+00:00",
                        "is-read": false
                    },
                    "type": "notification",
                    "id": "1",
                    "links": {
                        "self": "/v1/notifications/1"
                    }
                }
            ],
            "jsonapi": {
                "version": "1.0"
            },
            "links": {
                "self": "/v1/notifications"
            }
        }


## Notification Detail [/v1/notifications/{notification_id}]
+ Parameters
    + notification_id: 1 (integer) - ID of the notification in the form of an integer

### Notification Detail [GET]
Get a single notification.

+ Request

    + Headers

            Accept: application/vnd.api+json

            Authorization: JWT <Auth Key>

+ Response 200 (application/vnd.api+json)

        {
            "data": {
                "relationships": {
                    "user": {
                        "links": {
                            "self": "/v1/notifications/1/relationships/user",
                            "related": "/v1/notifications/1/user"
                        }
                    }
                },
                "attributes": {
                    "created-at": "2017-06-23T04:40:37.239724+00:00",
                    "is-read": false
                },
                "type": "notification",
                "id": "1"
            },
            "jsonapi": {
                "version": "1.0"
            }
        }


### Update Notification [PATCH]
Update a single notification with `id`.

+ `id` (integer) - ID of the record to update **(required)**

+ Request (application/vnd.api+json)

    + Headers

            Authorization: JWT <Auth Key>

    + Body

            {
              "data": {
                "attributes": {
                  "is-read": true
                },
                "type": "notification",
                "id": "1"
              }
            }

+ Response 200 (application/vnd.api+json)

        {
            "data": {
                "relationships": {
                    "user": {
                        "links": {
                            "self": "/v1/notifications/1/relationships/user",
                            "related": "/v1/notifications/1/user"
                        }
                    }
                },
                "attributes": {
                    "created-at": "2017-06-23T04:40:37.239724+00:00",
                    "is-read": true
                },
                "type": "notification",
                "id": "1"
            },
            "jsonapi": {
                "version": "1.0"
            }
        }

### Delete Notification [DELETE]
Delete a single notification.

+ Request

    + Headers

            Accept: application/vnd.api+json

            Authorization: JWT <Auth Key>

+ Response 200 (application/vnd.api+json)

        {
          "meta": {
            "message": "Object successfully deleted"
          },
          "jsonapi": {
            "version": "1.0"
          }
        }
