FORMAT: V1
HOST: https://api.eventyay.com

# Open Event API Server

The Open Event API Server

<!-- include(blueprint/auth/authentication.apib) -->

<!-- include(blueprint/user/users.apib) -->

<!-- include(blueprint/event/event_locations.apib) -->

<!-- include(blueprint/event/event_types.apib) -->

<!-- include(blueprint/event/event_topics.apib) -->

<!-- include(blueprint/event/event_sub_topics.apib) -->

<!-- include(blueprint/custom_placeholders.apib) -->

<!-- include(blueprint/event/events.apib) -->

<!-- include(blueprint/groups.apib) -->

<!-- include(blueprint/copyright.apib) -->

<!-- include(blueprint/invoices.apib) -->

<!-- include(blueprint/microlocations.apib) -->

<!-- include(blueprint/session/sessions.apib) -->

<!-- include(blueprint/session/session_type.apib) -->

<!-- include(blueprint/speaker/speakers.apib) -->

<!-- include(blueprint/social_links.apib) -->

<!-- include(blueprint/speaker/speaker_calls.apib) -->

<!-- include(blueprint/sponsors.apib) -->

<!-- include(blueprint/exhibitors.apib) -->

<!-- include(blueprint/tax.apib) -->

<!-- include(blueprint/ticket/tickets.apib) -->

<!-- include(blueprint/ticket/ticket_tags.apib) -->

<!-- include(blueprint/attendees.apib) -->

<!-- include(blueprint/ticket/ticket_fees.apib) -->

<!-- include(blueprint/tracks.apib) -->

<!-- include(blueprint/notification/notifications.apib) -->

<!-- include(blueprint/notification/email_notifications.apib) -->

<!-- include(blueprint/user/user_emails.apib) -->

<!-- include(blueprint/discount_codes.apib) -->

<!-- include(blueprint/access_codes.apib) -->

<!-- include(blueprint/role/role_invites.apib) -->

<!-- include(blueprint/role/users_events_roles.apib) -->

<!-- include(blueprint/image_size.apib) -->

<!-- include(blueprint/role/roles.apib) -->

<!-- include(blueprint/services.apib) -->

<!-- include(blueprint/event/event_role_permissions.apib) -->

<!-- include(blueprint/message_settings.apib) -->

<!-- include(blueprint/activity.apib) -->

<!-- include(blueprint/pages.apib) -->

<!-- include(blueprint/mails.apib) -->

<!-- include(blueprint/custom_forms.apib) -->

<!-- include(blueprint/faq/faqs.apib) -->

<!-- include(blueprint/faq/faq_types.apib) -->

<!-- include(blueprint/feedback.apib) -->

<!-- include(blueprint/user/user_permissions.apib) -->

<!-- include(blueprint/settings.apib) -->

<!-- include(blueprint/upload.apib) -->

<!-- include(blueprint/stripe_authorization.apib) -->

<!-- include(blueprint/event/event_export.apib) -->

<!-- include(blueprint/event/event_import.apib) -->

<!-- include(blueprint/celery_tasks.apib) -->

<!-- include(blueprint/event/event_statistics.apib) -->

<!-- include(blueprint/admin/admin_statistics.apib) -->

<!-- include(blueprint/order/order_statistics.apib) -->

<!-- include(blueprint/order/orders.apib) -->

<!-- include(blueprint/admin/admin_sales.apib) -->

<!-- include(blueprint/event/event_copy.apib) -->

<!-- include(blueprint/auth/change_password.apib) -->

<!-- include(blueprint/auth/email_verification.apib) -->

<!-- include(blueprint/custom_system_roles.apib) -->

<!-- include(blueprint/panel_permissions.apib) -->

<!-- include(blueprint/event/favourite_events.apib) -->

<!-- include(blueprint/import_jobs.apib) -->

<!-- include(blueprint/video_stream.apib) -->