FORMAT: V1
HOST: https://api.eventyay.com

# Open Event API Server

The Open Event API Server

<!-- include(blueprint/auth/authentication.apib) -->

<!-- include(blueprint/user/users.apib) -->

<!-- include(blueprint/station_store_pax.apib) -->