# Generated by Django 5.0 on 2024-03-12 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_description_visible', models.BooleanField(null=True)),
                ('type', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('sales_starts_at', models.DateTimeField()),
                ('sales_ends_at', models.DateTimeField()),
                ('is_hidden', models.BooleanField(null=True)),
                ('min_order', models.IntegerField(blank=True, null=True)),
                ('max_order', models.IntegerField(blank=True, null=True)),
                ('is_fee_absorbed', models.BooleanField(null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('auto_checkin_enabled', models.BooleanField(null=True)),
                ('is_checkin_restricted', models.BooleanField(null=True)),
                ('max_price', models.FloatField(blank=True, null=True)),
                ('min_price', models.FloatField(default=0)),
                ('form_id', models.CharField(blank=True, max_length=255, null=True)),
                ('badge_id', models.CharField(blank=True, max_length=255, null=True)),
                ('event_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event')),
            ],
        ),
    ]
