# Generated by Django 5.0 on 2023-12-23 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2147483647)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_description_visible', models.BooleanField(blank=True, null=True)),
                ('type', models.CharField(max_length=2147483647)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('sales_starts_at', models.DateTimeField(blank=True, null=True)),
                ('sales_ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_hidden', models.BooleanField(blank=True, null=True)),
                ('min_order', models.IntegerField(blank=True, null=True)),
                ('max_order', models.IntegerField(blank=True, null=True)),
                ('is_fee_absorbed', models.BooleanField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('auto_checkin_enabled', models.BooleanField(blank=True, null=True)),
                ('is_checkin_restricted', models.BooleanField(blank=True, null=True)),
                ('max_price', models.FloatField(blank=True, null=True)),
                ('min_price', models.FloatField(default=0)),
                ('form_id', models.CharField(blank=True, max_length=2147483647, null=True)),
                ('badge_id', models.CharField(blank=True, max_length=2147483647, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
            options={
                'unique_together': {('name', 'event', 'deleted_at')},
            },
        ),
    ]
