name: "Dependabot Approve - Action"

on:
  pull_request:

jobs:
  approve:
    runs-on: ubuntu-latest

    if: github.actor == 'dependabot-preview[bot]'
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              event: 'APPROVE'
            })
