# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - open-event-server

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: development

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Checkout master branch for pyproject.toml
        uses: actions/checkout@v4
        with:
          ref: master  # Checkout the 'master' branch to get the pyproject.toml
          path: master-branch

      - name: Copy pyproject.toml from master branch to development branch
        run: |
          cp master-branch/pyproject.toml .  # Copy the pyproject.toml file
          cp -r master-branch/scripts .
          cp -r master-branch/utils .
          cp -r master-branch/static .
          cp master-branch/package.json .
          cp master-branch/poetry.lock .
          cp master-branch/populate_db.py .
          cp master-branch/session_slides_type_to_json.py .
          cp master-branch/setup.cfg .
          cp master-branch/yarn.lock .

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies using Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          source ~/.profile  # Ensure Poetry is in PATH
          poetry install  # Install dependencies based on pyproject.toml
          sudo apt-get update
          sudo apt-get install libmagic1 libmagic-dev
          sudo apt-get install libpq-dev
          sudo apt-get install libcairo2 libcairo2-dev
          sudo apt-get update
          sudo apt-get install libpango-1.0-0 libpango1.0-dev
          
          

      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_25459C518E94458E9FFFC1EEB51BE4C9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_30C288E7351C44ADADF49E2BF7F2C108 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_482C86EA4AE84C4B93BBCEAE71C65AB0 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'open-event-server'
          slot-name: 'Production'
          
