# Ref: https://github.com/docker/build-push-action#usage
name: Build Docker container

on:
  push:
    branches:
      - 'feature/gh-action-build-docker'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: hongquan/eventyay:development
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
