# Ref: https://github.com/docker/build-push-action#usage
name: Build Docker container

on:
  push:
    branches:
      - development
      - master

jobs:
  docker:
    if: ${{ github.repository_owner == 'fossasia' }}
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to DockerHub
        # The job will terminate early if Docker Hub credentials is not set.
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Docker meta
        uses: docker/metadata-action@v3
        id: meta
        with:
          images: eventyay/open-event-server
      -
        name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
