# Ref: https://github.com/docker/build-push-action#usage
name: Build Docker container

on:
  push:
    branches:
      - development
      - feature/gh-action-build-docker

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Set Docker Hub namespace
        if: ${{ github.repository_owner == 'fossasia' }}
        env:
          DOCKERHUB_SPACE: eventyay
        run: echo $DOCKERHUB_SPACE
      -
        name: Set Docker Hub namespace
        if: ${{ github.repository_owner != 'fossasia' }}
        env:
          DOCKERHUB_SPACE: ${{ github.repository_owner }}
        run: echo $DOCKERHUB_SPACE
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker meta
        uses: docker/metadata-action@v3
        id: meta
        with:
          images: ${{ env.DOCKERHUB_SPACE }}/open-event-server
      -
        name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
